/* autogenerated by tools/build.py — не редактировать */
const {
  useState,
  useRef,
  useEffect,
  useCallback
} = React;
const SEG_COLORS = ['#6a8dff', '#34d399', '#ffb84f', '#ff5b8a', '#a06bff', '#4fd6ff', '#c9e04f', '#ff8a4f', '#5bffb0', '#fb6a6a', '#8a9bff', '#ffd75b'];

// =============================== i18n ======================================
const STR = {
  ru: {
    tagline: 'Адаптивные игровые лупы из любого трека: части зацикливаются, по кнопке «Дальше» трек развивается',
    upload_title: 'Трек',
    drop_hint: 'Перетащите аудиофайл сюда или кликните для выбора',
    drop_formats: 'mp3 · wav · ogg · flac · m4a …',
    drop_replace: '— кликните, чтобы заменить',
    track: 'Трек:',
    loading_upload: 'Отправка на сервер для анализа…',
    loading_decode: 'Декодирование аудио…',
    loading_analyze: 'Анализ структуры трека (темп, такты, секции)…',
    err_upload: 'Ошибка загрузки',
    err_analyze: 'Ошибка анализа',
    err_prefix: 'Ошибка:',
    err_markup: 'Не удалось прочитать разметку:',
    structure_title: 'Структура',
    tempo: 'Темп:',
    duration: 'Длительность:',
    parts: 'Частей:',
    fallback: 'ритм не найден — равномерная нарезка',
    snap: 'привязка к тактам',
    n_parts_ph: 'авто',
    n_parts_tip: 'Число частей',
    reanalyze: 'Переанализировать',
    ai_split_btn: 'Разделить с ИИ',
    engine_tip: 'Нейросеть All-In-One (обучена на 912 профессионально размеченных треках): точные границы и названия секций. Первый анализ ~1 мин, повторный — мгновенно',
    loading_deep: 'ИИ анализирует трек…',
    ai_working: 'ИИ анализирует трек',
    ai_stage1: 'Подготовка аудио…',
    ai_stage2: 'Разделение на стемы (барабаны, бас, вокал)…',
    ai_stage3: 'Нейросеть ищет структуру…',
    ai_stage4: 'Оценка качества лупов…',
    export_markup: '⤓ Разметка',
    import_markup: '⤒ Разметка',
    export_tip: 'Скачать разметку частей в JSON',
    import_tip: 'Загрузить разметку из JSON',
    export_loops: '⤓ Лупы (zip)',
    export_loops_tip: 'Скачать все части отдельными WAV-файлами',
    exporting: 'Формирование zip с лупами…',
    export_downloading: 'Скачивание лупов:',
    err_export: 'Ошибка экспорта',
    loop_quality_tip: 'Качество лупа: насколько бесшовно эта часть зациклится',
    loop_toggle_tip: 'Зацикливать эту часть? Проигровки (нарастание перед новой темой) лучше играть один раз',
    transition_badge: 'проигровка',
    n_suggested: 'оптимально:',
    n_max: 'макс:',
    loopstart_hint: 'Alt+клик внутри части — начало повтора лупа (жёлтый маркер): первый проход играет с начала части, повторы — с маркера',
    split_btn: '✂ Разрезать',
    split_tip: 'Разрезать часть в текущей позиции (клавиша S). Позиция — плейхед или место клика; без позиции — середина выбранной части. Граница привязывается к такту',
    split_seg_tip: 'Разрезать эту часть пополам (по ближайшему такту)',
    trans_mode: 'Переход:',
    mode_loop: 'конец лупа',
    mode_phrase: 'конец фразы',
    mode_loop_tip: 'Дождаться конца текущего лупа и перейти бесшовно',
    mode_phrase_tip: 'Перейти на ближайшей границе музыкальной фразы (4 или 8 тактов), не дожидаясь конца лупа',
    phrase_len_tip: 'Длина фразы: переход произойдёт на кратной границе от начала лупа',
    bars: 'такта',
    crossfade: 'Кроссфейд:',
    wave_hint: /*#__PURE__*/React.createElement("span", null, "\u041A\u043B\u0438\u043A \u2014 \u043F\u0435\u0440\u0435\u043C\u043E\u0442\u043A\u0430 \xB7 \u0417\u0435\u043B\u0451\u043D\u044B\u0439 \u043F\u043E\u043B\u0437\u0443\u043D\u043E\u043A \u2014 \u043F\u043E\u0437\u0438\u0446\u0438\u044F \xB7 \u0411\u0435\u043B\u0430\u044F \u0433\u0440\u0430\u043D\u0438\u0446\u0430 \u2014 \u043F\u0435\u0440\u0435\u0442\u0430\u0449\u0438\u0442\u044C \xB7 \u0414\u0432\u043E\u0439\u043D\u043E\u0439 \u043A\u043B\u0438\u043A \u2014 \u0440\u0430\u0437\u0440\u0435\u0437\u0430\u0442\u044C \xB7 Alt+\u043A\u043B\u0438\u043A \u2014 \u043D\u0430\u0447\u0430\u043B\u043E \u043F\u043E\u0432\u0442\u043E\u0440\u0430 \u043B\u0443\u043F\u0430 (\u0436\u0451\u043B\u0442\u044B\u0439 \u043C\u0430\u0440\u043A\u0435\u0440) \xB7 \u041A\u043E\u043B\u0435\u0441\u043E \u2014 \u0437\u0443\u043C, \u043F\u043E\u043B\u0437\u0443\u043D\u043E\u043A \u0441\u043D\u0438\u0437\u0443 \u2014 \u043F\u0440\u043E\u043A\u0440\u0443\u0442\u043A\u0430 \xB7 \u0416\u0451\u043B\u0442\u044B\u0435 \u043C\u0435\u0442\u043A\u0438 \u2014 \u043A\u0430\u0436\u0434\u044B\u0435 4 \u0442\u0430\u043A\u0442\u0430 (\u043D\u043E\u043C\u0435\u0440 \u0444\u0440\u0430\u0437\u044B) \xB7 \u0428\u0442\u0440\u0438\u0445\u043E\u0432\u043A\u0430 \u2014 \u043F\u0440\u043E\u0438\u0433\u0440\u043E\u0432\u043A\u0430 (\u0438\u0433\u0440\u0430\u0435\u0442 1 \u0440\u0430\u0437)"),
    del_seg: 'Удалить границу (слить с предыдущей)',
    player_title: 'Плеер',
    play: '▶ Играть (зациклить часть)',
    stop: '■ Стоп',
    next: 'Дальше →',
    next_armed: 'Переход в конце лупа…',
    playing: 'Играет:',
    pass: 'проход №',
    transition_planned: '· переход запланирован',
    selected: 'Выбрана часть:',
    keys_hint: /*#__PURE__*/React.createElement("span", null, /*#__PURE__*/React.createElement("kbd", null, "\u041F\u0440\u043E\u0431\u0435\u043B"), " \u2014 \u0438\u0433\u0440\u0430\u0442\u044C/\u0441\u0442\u043E\u043F \xB7 ", /*#__PURE__*/React.createElement("kbd", null, "\u2192"), " / ", /*#__PURE__*/React.createElement("kbd", null, "Enter"), " \u2014 \xAB\u0414\u0430\u043B\u044C\u0448\u0435\xBB \xB7 ", /*#__PURE__*/React.createElement("kbd", null, "S"), " \u2014 \u0440\u0430\u0437\u0440\u0435\u0437\u0430\u0442\u044C \u0432 \u043F\u043E\u0437\u0438\u0446\u0438\u0438 \xB7 ", /*#__PURE__*/React.createElement("kbd", null, "Ctrl+Z"), " \u2014 \u043E\u0442\u043C\u0435\u043D\u0438\u0442\u044C \u043F\u0440\u0430\u0432\u043A\u0443. \u041F\u0435\u0440\u0435\u0445\u043E\u0434 \u043F\u0440\u043E\u0438\u0441\u0445\u043E\u0434\u0438\u0442 \u0431\u0435\u0441\u0448\u043E\u0432\u043D\u043E \u043D\u0430 \u0433\u0440\u0430\u043D\u0438\u0446\u0435 \u043B\u0443\u043F\u0430, \u043A\u0430\u043A \u0432 \u0438\u0433\u0440\u043E\u0432\u044B\u0445 \u0441\u0430\u0443\u043D\u0434\u0442\u0440\u0435\u043A\u0430\u0445."),
    part: 'Часть',
    history_title: 'История',
    library_title: 'Библиотека ★',
    fav_btn: 'В библиотеку',
    fav_in_lib: 'В библиотеке',
    fav_add_tip: 'Сохранить в библиотеку — понравившиеся треки с разметкой всегда под рукой',
    fav_remove_tip: 'Убрать из библиотеки',
    history_open_tip: 'Открыть трек с сохранённой разметкой',
    history_del_tip: 'Удалить трек из истории',
    history_parts: 'ч.',
    loading_history: 'Загрузка трека из истории…',
    volume_tip: 'Громкость (клик по иконке — выкл/вкл)',
    beep_tip: 'Тест звука: короткий бип напрямую в аудиовыход',
    files_menu: '⤓⤒ Файлы',
    tail_label: 'хвост перехода',
    tail_tip: 'Реверберация/затухание старой части дозвучивает поверх новой (~1.2с) — главный убийца «дёрганых» стыков',
    bass_swap_label: 'бас-своп',
    bass_swap_tip: 'Бас новой части включается ровно на границе, а не в кроссфейде — не будет каши из двух басов',
    stinger_label: 'Стингер:',
    stinger_tip: 'Одиночный звук-акцент на переходе — как удар при входе в новую локацию',
    stinger_none: 'нет',
    stinger_cymbal: 'тарелка',
    stinger_boom: 'удар',
    stinger_riser: 'райзер',
    stems_label: 'Слои:',
    stems_tip: 'ИИ разделит трек на 4 слоя (барабаны/бас/вокал/фон) — ползунок интенсивности включает их постепенно, как в игровых саундтреках',
    stems_btn: 'Разделить на слои',
    stems_working: 'Разделение…',
    stems_ready: 'слои готовы',
    stems_off: 'выкл',
    stems_loading: 'ИИ разделяет трек на слои (~1 мин)…',
    stems_downloading: 'Загрузка слоя',
    intensity_label: 'Интенсивность:',
    int_calm: 'фон',
    int_low: '+бас',
    int_mid: '+ритм',
    int_full: 'всё',
    url_placeholder: 'Ссылка на YouTube / прямая ссылка на аудио…',
    url_btn: 'Импорт',
    url_downloading: 'Скачивание по ссылке…',
    loading_transcode: 'Браузер обрезал аудио — беру полный WAV с сервера…',
    footer: 'musslop — структурный анализ: beat tracking + novelty-сегментация (Foote)'
  },
  en: {
    tagline: 'Adaptive game-style loops from any track: sections loop forever, hit “Next” and the track evolves',
    upload_title: 'Track',
    drop_hint: 'Drop an audio file here or click to browse',
    drop_formats: 'mp3 · wav · ogg · flac · m4a …',
    drop_replace: '— click to replace',
    track: 'Track:',
    loading_upload: 'Uploading to server for analysis…',
    loading_decode: 'Decoding audio…',
    loading_analyze: 'Analyzing track structure (tempo, bars, sections)…',
    err_upload: 'Upload failed',
    err_analyze: 'Analysis failed',
    err_prefix: 'Error:',
    err_markup: 'Failed to read markup:',
    structure_title: 'Structure',
    tempo: 'Tempo:',
    duration: 'Duration:',
    parts: 'Parts:',
    fallback: 'no rhythm found — uniform split',
    snap: 'snap to bars',
    n_parts_ph: 'auto',
    n_parts_tip: 'Number of parts',
    reanalyze: 'Re-analyze',
    ai_split_btn: 'Split with AI',
    engine_tip: 'All-In-One neural net (trained on 912 professionally annotated tracks): accurate boundaries and section names. First run ~1 min, repeat — instant',
    loading_deep: 'AI is analyzing the track…',
    ai_working: 'AI is analyzing the track',
    ai_stage1: 'Preparing audio…',
    ai_stage2: 'Separating stems (drums, bass, vocals)…',
    ai_stage3: 'Neural net is finding the structure…',
    ai_stage4: 'Scoring loop quality…',
    export_markup: '⤓ Markup',
    import_markup: '⤒ Markup',
    export_tip: 'Download segment markup as JSON',
    import_tip: 'Load segment markup from JSON',
    export_loops: '⤓ Loops (zip)',
    export_loops_tip: 'Download all parts as separate WAV files',
    exporting: 'Building zip with loops…',
    export_downloading: 'Downloading loops:',
    err_export: 'Export failed',
    loop_quality_tip: 'Loop quality: how seamlessly this part will loop',
    loop_toggle_tip: 'Loop this part? Build-ups (rising transitions into a new theme) are better played once',
    transition_badge: 'build-up',
    n_suggested: 'suggested:',
    n_max: 'max:',
    loopstart_hint: 'Alt+click inside a part — loop repeat start (yellow marker): first pass plays from the part start, repeats from the marker',
    split_btn: '✂ Split',
    split_tip: 'Split the part at the current position (hotkey S). Position = playhead or last click; falls back to the middle of the selected part. Boundary snaps to a bar',
    split_seg_tip: 'Split this part in half (snapped to the nearest bar)',
    trans_mode: 'Transition:',
    mode_loop: 'loop end',
    mode_phrase: 'phrase end',
    mode_loop_tip: 'Wait for the current loop to finish, then advance seamlessly',
    mode_phrase_tip: 'Advance at the nearest musical phrase boundary (4 or 8 bars) without waiting for the loop end',
    phrase_len_tip: 'Phrase length: transition happens on a multiple of this from the loop start',
    bars: 'bars',
    crossfade: 'Crossfade:',
    wave_hint: /*#__PURE__*/React.createElement("span", null, "Click \u2014 seek \xB7 Green handle \u2014 position \xB7 White boundary \u2014 drag \xB7 Double click \u2014 split \xB7 Alt+click \u2014 loop repeat start (yellow marker) \xB7 Wheel \u2014 zoom, bottom scrollbar \u2014 pan \xB7 Yellow ticks \u2014 every 4 bars (phrase number) \xB7 Hatching \u2014 build-up (plays once)"),
    del_seg: 'Remove boundary (merge with previous)',
    player_title: 'Player',
    play: '▶ Play (loop part)',
    stop: '■ Stop',
    next: 'Next →',
    next_armed: 'Advancing at loop end…',
    playing: 'Playing:',
    pass: 'pass #',
    transition_planned: '· transition scheduled',
    selected: 'Selected part:',
    keys_hint: /*#__PURE__*/React.createElement("span", null, /*#__PURE__*/React.createElement("kbd", null, "Space"), " \u2014 play/stop \xB7 ", /*#__PURE__*/React.createElement("kbd", null, "\u2192"), " / ", /*#__PURE__*/React.createElement("kbd", null, "Enter"), " \u2014 \u201CNext\u201D \xB7 ", /*#__PURE__*/React.createElement("kbd", null, "S"), " \u2014 split at position \xB7 ", /*#__PURE__*/React.createElement("kbd", null, "Ctrl+Z"), " \u2014 undo edit. The transition is seamless at the loop boundary, just like in game soundtracks."),
    part: 'Part',
    history_title: 'History',
    library_title: 'Library ★',
    fav_btn: 'Add to library',
    fav_in_lib: 'In library',
    fav_add_tip: 'Save to library — keep favorite tracks with their markup at hand',
    fav_remove_tip: 'Remove from library',
    history_open_tip: 'Open track with saved markup',
    history_del_tip: 'Remove track from history',
    history_parts: 'parts',
    loading_history: 'Loading track from history…',
    volume_tip: 'Volume (click icon to mute/unmute)',
    beep_tip: 'Sound test: a short beep straight to the audio output',
    files_menu: '⤓⤒ Files',
    tail_label: 'transition tail',
    tail_tip: 'Reverb/decay of the old section rings out over the new one (~1.2s) — the main cure for jerky seams',
    bass_swap_label: 'bass swap',
    bass_swap_tip: 'The incoming bass enters exactly on the boundary, not inside the crossfade — no two-bass mud',
    stinger_label: 'Stinger:',
    stinger_tip: 'One-shot accent on the transition — like a hit when entering a new location',
    stinger_none: 'none',
    stinger_cymbal: 'cymbal',
    stinger_boom: 'boom',
    stinger_riser: 'riser',
    stems_label: 'Layers:',
    stems_tip: 'AI splits the track into 4 layers (drums/bass/vocals/backing) — the intensity slider brings them in gradually, like game soundtracks do',
    stems_btn: 'Split into layers',
    stems_working: 'Splitting…',
    stems_ready: 'layers ready',
    stems_off: 'off',
    stems_loading: 'AI is splitting the track into layers (~1 min)…',
    stems_downloading: 'Downloading layer',
    intensity_label: 'Intensity:',
    int_calm: 'ambient',
    int_low: '+bass',
    int_mid: '+drums',
    int_full: 'full',
    url_placeholder: 'YouTube link / direct audio URL…',
    url_btn: 'Import',
    url_downloading: 'Downloading from URL…',
    loading_transcode: 'Browser truncated the audio — fetching full WAV from server…',
    footer: 'musslop — structure analysis: beat tracking + novelty segmentation (Foote)'
  },
  zh: {
    tagline: '把任意乐曲变成自适应游戏配乐：段落无限循环，点击「下一段」音乐无缝推进',
    upload_title: '音轨',
    drop_hint: '将音频文件拖到此处，或点击选择文件',
    drop_formats: 'mp3 · wav · ogg · flac · m4a …',
    drop_replace: '— 点击替换',
    track: '音轨：',
    loading_upload: '正在上传到服务器进行分析…',
    loading_decode: '正在解码音频…',
    loading_analyze: '正在分析乐曲结构（速度、小节、段落）…',
    err_upload: '上传失败',
    err_analyze: '分析失败',
    err_prefix: '错误：',
    err_markup: '无法读取标注文件：',
    structure_title: '结构',
    tempo: '速度：',
    duration: '时长：',
    parts: '段落数：',
    fallback: '未检测到节奏 — 均匀切分',
    snap: '对齐小节',
    n_parts_ph: '自动',
    n_parts_tip: '段落数量',
    reanalyze: '重新分析',
    ai_split_btn: 'AI 智能分段',
    engine_tip: 'All-In-One 神经网络（用912首专业标注曲目训练）：边界和段落名称更准确。首次分析约1分钟，之后即时完成',
    loading_deep: 'AI 正在分析音轨…',
    ai_working: 'AI 正在分析音轨',
    ai_stage1: '正在准备音频…',
    ai_stage2: '正在分离音轨（鼓、贝斯、人声）…',
    ai_stage3: '神经网络正在识别结构…',
    ai_stage4: '正在评估循环质量…',
    export_markup: '⤓ 标注',
    import_markup: '⤒ 标注',
    export_tip: '将段落标注下载为 JSON',
    import_tip: '从 JSON 加载段落标注',
    export_loops: '⤓ 循环片段 (zip)',
    export_loops_tip: '将所有段落下载为独立的 WAV 文件',
    exporting: '正在打包循环片段…',
    export_downloading: '正在下载循环片段:',
    err_export: '导出失败',
    loop_quality_tip: '循环质量：该段落循环时的无缝程度',
    loop_toggle_tip: '循环此段落？渐强过渡段（build-up）只播放一次效果更好',
    transition_badge: '过渡段',
    n_suggested: '建议：',
    n_max: '最大：',
    loopstart_hint: 'Alt+点击段落内部 — 设置循环起点（黄色标记）：首次播放从段落开头开始，重复时从标记处开始',
    split_btn: '✂ 切分',
    split_tip: '在当前位置切分段落（快捷键 S）。位置 = 播放头或点击处；若无则取所选段落的中点。边界自动对齐小节',
    split_seg_tip: '将此段落对半切分（对齐最近的小节）',
    trans_mode: '切换方式：',
    mode_loop: '循环结尾',
    mode_phrase: '乐句结尾',
    mode_loop_tip: '等当前循环播完后无缝切换',
    mode_phrase_tip: '在最近的乐句边界（4 或 8 小节）切换，无需等循环结束',
    phrase_len_tip: '乐句长度：切换发生在距循环起点该长度的整数倍处',
    bars: '小节',
    crossfade: '交叉淡化：',
    wave_hint: /*#__PURE__*/React.createElement("span", null, "\u70B9\u51FB \u2014 \u5B9A\u4F4D \xB7 \u7EFF\u8272\u6ED1\u5757 \u2014 \u64AD\u653E\u4F4D\u7F6E \xB7 \u767D\u8272\u8FB9\u754C \u2014 \u62D6\u52A8\u8C03\u6574 \xB7 \u53CC\u51FB \u2014 \u5207\u5206 \xB7 Alt+\u70B9\u51FB \u2014 \u5FAA\u73AF\u8D77\u70B9\uFF08\u9EC4\u8272\u6807\u8BB0\uFF09 \xB7 \u6EDA\u8F6E \u2014 \u7F29\u653E\uFF0C\u5E95\u90E8\u6ED1\u5757 \u2014 \u5E73\u79FB \xB7 \u9EC4\u8272\u523B\u5EA6 \u2014 \u6BCF 4 \u5C0F\u8282\uFF08\u4E50\u53E5\u7F16\u53F7\uFF09 \xB7 \u659C\u7EBF\u9634\u5F71 \u2014 \u8FC7\u6E21\u6BB5\uFF08\u53EA\u64AD\u4E00\u6B21\uFF09"),
    del_seg: '删除边界（与前一段合并）',
    player_title: '播放器',
    play: '▶ 播放（循环此段）',
    stop: '■ 停止',
    next: '下一段 →',
    next_armed: '将在循环结尾切换…',
    playing: '正在播放：',
    pass: '第',
    pass_suffix: '遍',
    transition_planned: '· 已计划切换',
    selected: '已选段落:',
    keys_hint: /*#__PURE__*/React.createElement("span", null, /*#__PURE__*/React.createElement("kbd", null, "\u7A7A\u683C"), " \u2014 \u64AD\u653E/\u505C\u6B62 \xB7 ", /*#__PURE__*/React.createElement("kbd", null, "\u2192"), " / ", /*#__PURE__*/React.createElement("kbd", null, "Enter"), " \u2014 \u300C\u4E0B\u4E00\u6BB5\u300D \xB7 ", /*#__PURE__*/React.createElement("kbd", null, "S"), " \u2014 \u5728\u5F53\u524D\u4F4D\u7F6E\u5207\u5206 \xB7 ", /*#__PURE__*/React.createElement("kbd", null, "Ctrl+Z"), " \u2014 \u64A4\u9500\u7F16\u8F91\u3002\u5207\u6362\u5728\u5FAA\u73AF\u8FB9\u754C\u5904\u65E0\u7F1D\u5B8C\u6210\uFF0C\u5C31\u50CF\u6E38\u620F\u914D\u4E50\u4E00\u6837\u3002"),
    part: '段落',
    history_title: '历史记录',
    library_title: '收藏库 ★',
    fav_btn: '加入收藏库',
    fav_in_lib: '已收藏',
    fav_add_tip: '保存到收藏库 — 随时快速打开喜欢的音轨及其标注',
    fav_remove_tip: '从收藏库移除',
    history_open_tip: '打开带有已保存标注的音轨',
    history_del_tip: '从历史记录中删除',
    history_parts: '段',
    loading_history: '正在从历史记录加载音轨…',
    volume_tip: '音量（点击图标静音/取消静音）',
    beep_tip: '声音测试：直接向音频输出发送短促提示音',
    files_menu: '⤓⤒ 文件',
    tail_label: '过渡尾音',
    tail_tip: '旧段落的混响/衰减在新段落上延续（约1.2秒）— 消除生硬接缝的关键',
    bass_swap_label: '贝斯切换',
    bass_swap_tip: '新段落的贝斯恰好在边界处进入，而非在交叉淡化中 — 避免双贝斯浑浊',
    stinger_label: '重音音效:',
    stinger_tip: '过渡时的单次重音 — 如同进入新场景时的音效',
    stinger_none: '无',
    stinger_cymbal: '镲片',
    stinger_boom: '低音鼓',
    stinger_riser: '上升音',
    stems_label: '分层:',
    stems_tip: 'AI 将音轨分为4层（鼓/贝斯/人声/伴奏）— 强度滑块逐层加入，如同游戏配乐',
    stems_btn: 'AI 分层',
    stems_working: '正在分离…',
    stems_ready: '分层就绪',
    stems_off: '关闭',
    stems_loading: 'AI 正在分层（约1分钟）…',
    stems_downloading: '正在下载分层',
    intensity_label: '强度:',
    int_calm: '氛围',
    int_low: '+贝斯',
    int_mid: '+鼓点',
    int_full: '全部',
    url_placeholder: 'YouTube 链接 / 音频直链…',
    url_btn: '导入',
    url_downloading: '正在从链接下载…',
    loading_transcode: '浏览器截断了音频 — 正在从服务器获取完整 WAV…',
    footer: 'musslop — 结构分析：节拍跟踪 + 新颖度分段（Foote）'
  }
};
function fmt(t) {
  if (t == null || isNaN(t)) return '–';
  const m = Math.floor(t / 60),
    s = t % 60;
  return `${m}:${s.toFixed(1).padStart(4, '0')}`;
}

// ============================ Player (Web Audio) ===========================
// Each loop pass is scheduled as a separate AudioBufferSourceNode with
// sample-accurate start; micro-fades (6 ms) remove clicks at seams.
// "Next" — the next scheduled chunk is taken from the next section.
class LoopPlayer {
  constructor() {
    this.ctx = null;
    this.buffer = null;
    this.segments = [];
    this.downbeats = [];
    this.playing = false;
    this.segIndex = 0;
    this.advanceArmed = false;
    this.loopEnabled = true;
    this.crossfade = 0; // сек, 0 = стык по границе с микро-фейдом
    this.transitionMode = 'loop'; // 'loop' = в конце лупа, 'phrase' = граница фразы
    this.phraseBars = 4; // длина фразы в тактах для режима 'phrase'
    this.tailEnabled = true; // post-exit: хвост старой части дозвучивает
    this.TAIL = 1.2; // сек хвоста
    this.bassSwap = true; // бас входящей части включается на границе
    this.stinger = 'none'; // 'none' | 'cymbal' | 'boom' | 'riser'
    this.stingerBuffers = {}; // name -> AudioBuffer
    this.stems = null; // {drums,bass,other,vocals: AudioBuffer} | null
    this.stemGains = null; // {name: GainNode}
    this.intensity = 1; // 0..1, влияет на слои стемов
    this.nextTime = 0; // ctx time of the next chunk start
    this.queue = []; // [{t0, t1, segIndex, trackStart}]
    this.sources = []; // [{src, g}]
    this.timer = null;
    this.loopCount = 0;
    this.pendingPos = null; // позиция, выбранная кликом до запуска
    this.onState = () => {};
    this.FADE = 0.006;
    this.LOOKAHEAD = 0.35; // sec of scheduling lookahead
    this._reschedT = null;
  }
  _ensureCtx() {
    if (!this.ctx) {
      this.ctx = new (window.AudioContext || window.webkitAudioContext)();
      this.master = this.ctx.createGain();
      this.master.gain.value = this.volume != null ? this.volume : 1;
      this.master.connect(this.ctx.destination);
      if (this.loadStingers) this.loadStingers();
    }
    if (this.ctx.state === 'suspended') this.ctx.resume();
  }
  setVolume(v) {
    this.volume = v;
    if (this.master) {
      const now = this.ctx.currentTime;
      this.master.gain.cancelScheduledValues(now);
      this.master.gain.setValueAtTime(this.master.gain.value, now);
      this.master.gain.linearRampToValueAtTime(v, now + 0.03);
    }
  }
  setSegments(segs) {
    const prevSig = this._segSig;
    this._segSig = segs.map(s => `${s.start.toFixed(3)}_${s.end.toFixed(3)}_${s.loopStart != null ? s.loopStart.toFixed(3) : ''}_${s.loop === false ? 0 : 1}`).join('|');
    this.segments = segs;
    if (this.segIndex >= segs.length) this.segIndex = Math.max(0, segs.length - 1);
    // перепланируем только если реально изменились границы/флаги,
    // а не метаданные (loopability, label)
    if (this.playing && prevSig !== undefined && prevSig !== this._segSig) {
      clearTimeout(this._reschedT);
      this._reschedT = setTimeout(() => {
        if (!this.playing) return;
        this._replan();
      }, 120);
    }
  }
  // Мягко погасить и остановить источники (вместо жёсткого stop -> щелчки)
  _fadeStopAll(fade = 0.05) {
    const now = this.ctx.currentTime;
    for (const r of this.sources) {
      try {
        if (r.when > now + 0.005) {
          (r.stopAll || (t => r.src.stop(t)))(now);
          continue;
        } // ещё не стартовал
        const g = r.g.gain;
        g.cancelScheduledValues(now);
        g.setValueAtTime(g.value, now);
        g.linearRampToValueAtTime(0, now + fade);
        (r.stopAll || (t => r.src.stop(t)))(now + fade + 0.01);
      } catch (e) {
        try {
          (r.stopAll || (() => r.src.stop()))();
        } catch (e2) {}
      }
    }
    this.sources = [];
  }
  // Перепланирование на лету: текущий кусок продолжает звучать, его конец
  // подгоняется под новую границу, будущие куски отменяются и строятся заново.
  _replan() {
    if (!this.playing || !this.buffer || !this.segments.length) return;
    const now = this.ctx.currentTime;
    const pos = this.position();
    if (pos == null) return;
    const idx = this._segAt(pos);
    const seg = this.segments[idx];
    // текущий звучащий источник (самый поздний из уже стартовавших)
    let cur = null;
    for (const r of this.sources) {
      if (r.when <= now + 0.005 && (!cur || r.when > cur.when)) cur = r;
    }
    // границу утащили за плейхед или источник не найден — мягкий перезапуск
    if (!cur || pos >= seg.end - 0.08 || pos < seg.start - 0.05) {
      this._softRestartAt(Math.max(seg.start, Math.min(pos, seg.end - 0.1)));
      return;
    }
    // отменить будущие куски (они ещё не звучат — тишина без артефактов)
    for (const r of this.sources) {
      if (r !== cur && r.when > now + 0.005) {
        try {
          (r.stopAll || (t => r.src.stop(t)))(now);
        } catch (e) {}
      }
    }
    this.sources = this.sources.filter(r => r === cur || r.when <= now + 0.005);
    // подогнать конец текущего куска под новую границу сегмента
    const newEndCtx = cur.when + (seg.end - cur.from);
    try {
      const g = cur.g.gain;
      g.cancelScheduledValues(now);
      g.setValueAtTime(g.value, now);
      g.linearRampToValueAtTime(1, now + 0.02);
      g.setValueAtTime(1, Math.max(now + 0.02, newEndCtx - this.FADE));
      g.linearRampToValueAtTime(0, newEndCtx);
      (cur.stopAll || (t => cur.src.stop(t)))(newEndCtx + 0.02);
      cur.end = seg.end;
    } catch (e) {
      // браузер не дал перенести stop — тогда мягкий перезапуск
      this._softRestartAt(pos);
      return;
    }
    const prevFlags = this.queue.length ? this.queue[0] : {};
    this.queue = [{
      t0: cur.when,
      t1: newEndCtx,
      segIndex: idx,
      trackStart: cur.from,
      isLoopRepeat: !!prevFlags.isLoopRepeat
    }];
    this.segIndex = idx;
    this.lastPlannedIndex = idx;
    this.nextTime = newEndCtx;
    this.onState();
  }
  // Перезапуск с плавным затуханием старого (для seek и краевых случаев)
  _softRestartAt(pos) {
    this._fadeStopAll(0.05);
    if (!this.segments.length || !this.buffer) return;
    const idx = this._segAt(pos);
    const seg = this.segments[idx];
    const from = Math.max(seg.start, Math.min(pos, seg.end - 0.05));
    this.segIndex = idx;
    this.lastPlannedIndex = idx;
    this.nextTime = this.ctx.currentTime + 0.06;
    const dur = this._scheduleChunkRange(from, seg.end, this.nextTime, 0.03, null);
    this.queue = [{
      t0: this.nextTime,
      t1: this.nextTime + dur,
      segIndex: idx,
      trackStart: from,
      isLoopRepeat: false
    }];
    this.nextTime += dur;
    this.onState();
  }
  _segAt(pos) {
    let idx = this.segments.findIndex(s => pos >= s.start && pos < s.end);
    if (idx < 0) idx = this.segments.findIndex(s => pos < s.end);
    if (idx < 0) idx = this.segments.length - 1;
    return idx;
  }
  // Кусок аудио [from, to) на ctx-времени when.
  // fadeIn/fadeOut — длительности фейдов (equal-power при кроссфейде).
  // opts.bassDelay — сек: бас включается позже (бас-своп на переходе).
  _scheduleChunkRange(from, to, when, fadeIn = null, fadeOut = null, opts = {}) {
    const dur = to - from;
    if (dur <= 0.01) return 0;
    const g = this.ctx.createGain();
    const fi = Math.min(fadeIn != null ? fadeIn : this.FADE, dur / 2);
    const fo = Math.min(fadeOut != null ? fadeOut : this.FADE, dur / 2);
    g.gain.setValueAtTime(0, when);
    if (fi > 0.02) {
      // equal-power вход
      const N = 8;
      for (let k = 1; k <= N; k++) g.gain.linearRampToValueAtTime(Math.sin(k / N * Math.PI / 2), when + fi * k / N);
    } else {
      g.gain.linearRampToValueAtTime(1, when + fi);
    }
    g.gain.setValueAtTime(1, when + dur - fo);
    if (fo > 0.02) {
      const N = 8;
      for (let k = 1; k <= N; k++) g.gain.linearRampToValueAtTime(Math.cos(k / N * Math.PI / 2), when + dur - fo + fo * k / N);
    } else {
      g.gain.linearRampToValueAtTime(0, when + dur);
    }
    g.connect(this.master);
    const started = [];
    if (this.stems) {
      // мульти-стем: каждый слой через свой gain (интенсивность)
      this._ensureStemGains();
      for (const name of ['drums', 'bass', 'other', 'vocals']) {
        const buf = this.stems[name];
        if (!buf) continue;
        const s = this.ctx.createBufferSource();
        s.buffer = buf;
        const sg = this.stemGains[name];
        // бас-своп: bass и drums молчат до границы + fi, потом резкий вход
        if (opts.bassDelay && (name === 'bass' || name === 'drums')) {
          const dg = this.ctx.createGain();
          dg.gain.setValueAtTime(0, when);
          dg.gain.setValueAtTime(0, when + opts.bassDelay - 0.005);
          dg.gain.linearRampToValueAtTime(1, when + opts.bassDelay + 0.01);
          s.connect(dg);
          dg.connect(sg);
        } else {
          s.connect(sg);
        }
        sg.connect(g);
        s.start(when, Math.min(from, buf.duration - 0.01), dur);
        started.push(s);
      }
    } else {
      const src = this.ctx.createBufferSource();
      src.buffer = this.buffer;
      if (opts.bassDelay && this.bassSwap) {
        // без стемов: 2-полосный сплит, низ входит с задержкой
        const lo = this.ctx.createBiquadFilter();
        lo.type = 'lowpass';
        lo.frequency.value = 180;
        lo.Q.value = 0.7;
        const hi = this.ctx.createBiquadFilter();
        hi.type = 'highpass';
        hi.frequency.value = 180;
        hi.Q.value = 0.7;
        const loG = this.ctx.createGain();
        loG.gain.setValueAtTime(0, when);
        loG.gain.setValueAtTime(0, when + opts.bassDelay - 0.005);
        loG.gain.linearRampToValueAtTime(1, when + opts.bassDelay + 0.01);
        src.connect(lo);
        lo.connect(loG);
        loG.connect(g);
        src.connect(hi);
        hi.connect(g);
      } else {
        src.connect(g);
      }
      src.start(when, from, dur);
      started.push(src);
    }
    const rec = {
      src: started[0],
      srcs: started,
      g,
      when,
      from,
      end: to
    };
    this.sources.push(rec);
    started[0].onended = () => {
      this.sources = this.sources.filter(s => s !== rec);
    };
    // общий stop для мульти-источников
    rec.stopAll = t => started.forEach(s => {
      try {
        t != null ? s.stop(t) : s.stop();
      } catch (e) {}
    });
    return dur;
  }
  _ensureStemGains() {
    if (this.stemGains) return;
    this.stemGains = {};
    for (const name of ['drums', 'bass', 'other', 'vocals']) {
      const gn = this.ctx.createGain();
      this.stemGains[name] = gn;
    }
    this.setIntensity(this.intensity);
  }
  // Интенсивность 0..1 -> слои: other всегда, bass с 0.25, drums с 0.5, vocals с 0.75
  setIntensity(v) {
    this.intensity = v;
    if (!this.stemGains || !this.ctx) return;
    const now = this.ctx.currentTime;
    const layer = (gn, on) => {
      const target = on ? 1 : 0;
      gn.gain.cancelScheduledValues(now);
      gn.gain.setValueAtTime(gn.gain.value, now);
      gn.gain.linearRampToValueAtTime(target, now + 0.4);
    };
    layer(this.stemGains.other, true);
    layer(this.stemGains.bass, v >= 0.25);
    layer(this.stemGains.drums, v >= 0.5);
    layer(this.stemGains.vocals, v >= 0.75);
  }
  // Стингер: одиночный звук на моменте перехода
  _playStinger(when) {
    const buf = this.stingerBuffers[this.stinger];
    if (!buf) return;
    const src = this.ctx.createBufferSource();
    src.buffer = buf;
    const g = this.ctx.createGain();
    g.gain.value = 0.9;
    src.connect(g);
    g.connect(this.master);
    // райзер должен ЗАКОНЧИТЬСЯ на границе, удар/тарелка — начаться на ней
    const t = this.stinger === 'riser' ? Math.max(this.ctx.currentTime, when - buf.duration) : when;
    src.start(t);
  }
  // Post-exit: хвост старой части дозвучивает поверх начала новой с затуханием
  _schedulePostExitTail(fromPos, when) {
    if (!this.tailEnabled) return;
    const end = Math.min(fromPos + this.TAIL, this.buffer.duration);
    const dur = end - fromPos;
    if (dur <= 0.05) return;
    const src = this.ctx.createBufferSource();
    src.buffer = this.buffer;
    const g = this.ctx.createGain();
    const N = 8;
    g.gain.setValueAtTime(0.9, when);
    for (let k = 1; k <= N; k++) g.gain.linearRampToValueAtTime(0.9 * Math.cos(k / N * Math.PI / 2), when + dur * k / N);
    src.connect(g);
    g.connect(this.master);
    src.start(when, fromPos, dur);
    const rec = {
      src,
      srcs: [src],
      g,
      when,
      from: fromPos,
      end,
      isTail: true,
      stopAll: t => {
        try {
          t != null ? src.stop(t) : src.stop();
        } catch (e) {}
      }
    };
    this.sources.push(rec);
    src.onended = () => {
      this.sources = this.sources.filter(s => s !== rec);
    };
  }
  // Перезапуск с произвольной позиции трека (не сбрасывает playing)
  _restartAt(pos) {
    this.sources.forEach(s => {
      try {
        (s.stopAll || (() => s.src.stop()))();
      } catch (e) {}
    });
    this.sources = [];
    if (!this.segments.length || !this.buffer) return;
    const idx = this._segAt(pos);
    const seg = this.segments[idx];
    const from = Math.max(seg.start, Math.min(pos, seg.end - 0.05));
    this.segIndex = idx;
    this.lastPlannedIndex = idx;
    this.nextTime = this.ctx.currentTime + 0.06;
    const dur = this._scheduleChunkRange(from, seg.end, this.nextTime);
    this.queue = [{
      t0: this.nextTime,
      t1: this.nextTime + dur,
      segIndex: idx,
      trackStart: from,
      isLoopRepeat: false
    }];
    this.nextTime += dur;
    this.onState();
  }
  _tick() {
    if (!this.playing) return;
    const now = this.ctx.currentTime;
    while (this.queue.length > 1 && this.queue[1].t0 <= now) {
      this.queue.shift();
      const cur = this.queue[0];
      if (cur.isLoopRepeat) this.loopCount++;else this.loopCount = 1;
      this.segIndex = cur.segIndex;
      this.onState();
    }
    while (this.nextTime - now < this.LOOKAHEAD) {
      if (!this.segments.length) break;
      let idx = this.lastPlannedIndex;
      let isRepeat = true;
      const curSeg = this.segments[idx];
      // часть без лупа (проигровка) проигрывается один раз и идёт дальше
      const noLoop = curSeg && curSeg.loop === false;
      if (this.advanceArmed || !this.loopEnabled || noLoop) {
        if (idx + 1 < this.segments.length) {
          idx = idx + 1;
          isRepeat = false;
        } else {
          this.stop();
          this.onState();
          return;
        }
        this.advanceArmed = false;
        this.onState();
      }
      const seg = this.segments[idx];
      // повтор лупа начинается с loopStart (если задан), первый вход — с start
      const from = isRepeat && seg.loopStart != null && seg.loopStart > seg.start && seg.loopStart < seg.end - 0.5 ? seg.loopStart : seg.start;
      // Кроссфейд: куски перекрываются на xf — конец текущего затухает,
      // пока начало следующего нарастает (equal-power). Работает и на
      // повторах лупа (сглаживает стык конец->начало), и на переходах.
      const chunkDur = seg.end - from;
      const xf = this.crossfade > 0.02 ? Math.min(this.crossfade, chunkDur / 3) : 0;
      const isSectionChange = !isRepeat && this.lastPlannedIndex !== idx;
      const opts = {};
      if (isSectionChange && this.bassSwap) {
        // бас входящей части включается ровно на границе (не в кроссфейде)
        opts.bassDelay = Math.max(xf, 0.01);
      }
      const dur = this._scheduleChunkRange(from, seg.end, this.nextTime, xf > 0 ? xf : null, xf > 0 ? xf : null, opts);
      if (isSectionChange) {
        // post-exit: хвост прошлой части дозвучивает поверх новой
        const prev = this.segments[this.lastPlannedIndex];
        if (prev) this._schedulePostExitTail(prev.end, this.nextTime);
        // стингер на моменте перехода
        if (this.stinger !== 'none') this._playStinger(this.nextTime);
      }
      this.queue.push({
        t0: this.nextTime,
        t1: this.nextTime + dur,
        segIndex: idx,
        trackStart: from,
        isLoopRepeat: isRepeat && this.lastPlannedIndex === idx
      });
      this.lastPlannedIndex = idx;
      this.nextTime += dur - xf; // следующий кусок стартует внахлёст
    }
  }
  play(fromSeg = null) {
    this._ensureCtx();
    this.stop(false);
    if (fromSeg != null) {
      this.segIndex = fromSeg;
      this.pendingPos = null;
    }
    if (!this.segments.length || !this.buffer) return;
    this.playing = true;
    this.advanceArmed = false;
    this.loopCount = 1;
    const seg0 = this.segments[Math.min(this.segIndex, this.segments.length - 1)];
    const pos = this.pendingPos != null && fromSeg == null ? this.pendingPos : seg0.start;
    this.pendingPos = null;
    this.timer = setInterval(() => this._tick(), 60);
    this._restartAt(pos);
  }
  // Перемотка в произвольную точку трека (drag плейхеда / клик)
  seek(pos) {
    if (!this.segments.length) return;
    if (this.playing) {
      this.loopCount = 1;
      this.advanceArmed = false;
      this._softRestartAt(pos);
    } else {
      this.segIndex = this._segAt(pos);
      this.pendingPos = pos;
      this.onState();
    }
  }
  advance() {
    if (!this.playing) return;
    if (this.transitionMode === 'phrase' && this.downbeats.length) {
      this._advanceAtPhrase();
    } else {
      this.advanceArmed = true;
    }
    this.onState();
  }
  // Переход на границе музыкальной фразы (кратно phraseBars тактов от начала
  // текущего куска), не дожидаясь конца лупа. Такт — слишком мелкая единица:
  // тема должна завершиться, поэтому по умолчанию фраза = 4 такта.
  _advanceAtPhrase() {
    const pos = this.position();
    if (pos == null) return;
    if (this.segIndex + 1 >= this.segments.length) {
      this.advanceArmed = true;
      return;
    }
    const seg = this.segments[this.segIndex];
    const margin = 0.12; // сек на планирование
    // опорная точка отсчёта фраз — начало текущего прохода лупа
    const cur = this.queue.length ? this.queue[this.queue.length - 1] : null;
    const anchor = cur ? cur.trackStart : seg.start;
    // downbeats внутри части, начиная с якоря
    const dbs = this.downbeats.filter(b => b >= anchor - 0.05 && b < seg.end - 0.05);
    const nBars = this.phraseBars || 4;
    // кандидаты: каждый nBars-й downbeat от якоря
    let target = null;
    for (let k = nBars; k < dbs.length; k += nBars) {
      if (dbs[k] > pos + margin) {
        target = dbs[k];
        break;
      }
    }
    // фразовой границы впереди нет — доигрываем луп до конца (обычный режим)
    if (target == null) {
      this.advanceArmed = true;
      return;
    }
    const now = this.ctx.currentTime;
    const Tt = now + (target - pos);
    const nextSeg = this.segments[this.segIndex + 1];
    const xf = Math.max(this.crossfade, 0.03);
    // погасить всё текущее к моменту Tt (+xf хвост)
    this.sources.forEach(({
      g
    }) => {
      try {
        g.gain.cancelScheduledValues(Tt);
        g.gain.setValueAtTime(g.gain.value, Tt);
        const N = 6;
        for (let k = 1; k <= N; k++) g.gain.linearRampToValueAtTime(Math.cos(k / N * Math.PI / 2), Tt + xf * k / N);
      } catch (e) {}
    });
    const olds = this.sources.slice();
    setTimeout(() => olds.forEach(s => {
      try {
        (s.stopAll || (() => s.src.stop()))();
      } catch (e) {}
    }), (Tt - now + xf + 0.1) * 1000);
    this.sources = [];
    // новая часть с её начала
    this.nextTime = Tt;
    const dur = this._scheduleChunkRange(nextSeg.start, nextSeg.end, Tt, this.crossfade > 0.02 ? xf : null, null);
    this.queue = [{
      t0: now,
      t1: Tt,
      segIndex: this.segIndex,
      trackStart: pos,
      isLoopRepeat: false
    }, {
      t0: Tt,
      t1: Tt + dur,
      segIndex: this.segIndex + 1,
      trackStart: nextSeg.start,
      isLoopRepeat: false
    }];
    this.lastPlannedIndex = this.segIndex + 1;
    this.nextTime = Tt + dur;
  }
  stop(notify = true) {
    this.playing = false;
    this.advanceArmed = false;
    clearTimeout(this._reschedT);
    if (this.timer) {
      clearInterval(this.timer);
      this.timer = null;
    }
    this.sources.forEach(s => {
      try {
        (s.stopAll || (() => s.src.stop()))();
      } catch (e) {}
    });
    this.sources = [];
    this.queue = [];
    if (notify) this.onState();
  }
  position() {
    if (!this.playing || !this.ctx || !this.queue.length) return null;
    const now = this.ctx.currentTime;
    let cur = this.queue[0];
    for (const q of this.queue) if (q.t0 <= now) cur = q;
    if (now < cur.t0) return cur.trackStart;
    return cur.trackStart + (now - cur.t0);
  }
}

// ============================== Waveform ===================================
function Waveform({
  buffer,
  segments,
  setSegments,
  beats,
  downbeats,
  snap,
  player,
  playingSeg,
  duration,
  onSeekSeg,
  t,
  beginEdit,
  commitEdit,
  aiWorking
}) {
  const canvasRef = useRef(null);
  const peaksRef = useRef(null);
  const dragRef = useRef(null);
  const viewRef = useRef({
    t0: 0,
    t1: 0
  }); // видимое окно (сек); t1=0 -> весь трек
  const [, force] = useState(0);
  const H = 420;
  useEffect(() => {
    if (!buffer) {
      peaksRef.current = null;
      return;
    }
    const W = 8192; // достаточно для зума
    const data = buffer.getChannelData(0);
    const step = Math.max(1, Math.floor(data.length / W));
    const peaks = new Float32Array(W * 2);
    for (let i = 0; i < W; i++) {
      let mn = 1,
        mx = -1;
      const s = i * step,
        e = Math.min(s + step, data.length);
      for (let j = s; j < e; j += 2) {
        const v = data[j];
        if (v < mn) mn = v;
        if (v > mx) mx = v;
      }
      peaks[i * 2] = mn;
      peaks[i * 2 + 1] = mx;
    }
    peaksRef.current = {
      peaks,
      W
    };
    viewRef.current = {
      t0: 0,
      t1: 0
    };
    force(x => x + 1);
  }, [buffer]);
  const view = () => {
    const v = viewRef.current;
    return v.t1 > v.t0 ? v : {
      t0: 0,
      t1: duration || 1
    };
  };
  const segColor = (s, i) => {
    if (s.group) {
      const gi = s.group.charCodeAt(0) - 65;
      return SEG_COLORS[gi % SEG_COLORS.length];
    }
    return SEG_COLORS[i % SEG_COLORS.length];
  };
  const draw = useCallback(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const rect = canvas.getBoundingClientRect();
    const dpr = window.devicePixelRatio || 1;
    canvas.width = rect.width * dpr;
    canvas.height = H * dpr;
    const ctx = canvas.getContext('2d');
    ctx.scale(dpr, dpr);
    const W = rect.width;
    ctx.fillStyle = '#10141d';
    ctx.fillRect(0, 0, W, H);
    if (!duration) return;
    const {
      t0,
      t1
    } = view();
    const span = t1 - t0;
    const tx = tt => (tt - t0) / span * W;

    // segment backgrounds
    segments.forEach((s, i) => {
      if (s.end < t0 || s.start > t1) return;
      const c = segColor(s, i);
      ctx.fillStyle = c + (i === playingSeg ? '40' : '1c');
      ctx.fillRect(tx(s.start), 0, tx(s.end) - tx(s.start), H);
      // проигровка (без лупа): диагональная штриховка
      if (s.loop === false) {
        ctx.save();
        ctx.beginPath();
        ctx.rect(tx(s.start), 0, tx(s.end) - tx(s.start), H);
        ctx.clip();
        ctx.strokeStyle = '#ffffff14';
        ctx.beginPath();
        const step = 14;
        for (let x = tx(s.start) - H; x < tx(s.end); x += step) {
          ctx.moveTo(x, H);
          ctx.lineTo(x + H, 0);
        }
        ctx.stroke();
        ctx.restore();
      }
      // loopStart: жёлтый маркер внутри части
      if (s.loop !== false && s.loopStart != null && s.loopStart > s.start + 0.05) {
        const lx = tx(s.loopStart);
        ctx.strokeStyle = '#ffb84f';
        ctx.setLineDash([5, 4]);
        ctx.beginPath();
        ctx.moveTo(lx, 0);
        ctx.lineTo(lx, H);
        ctx.stroke();
        ctx.setLineDash([]);
        ctx.fillStyle = '#ffb84f';
        ctx.beginPath();
        ctx.moveTo(lx, 14);
        ctx.lineTo(lx + 8, 19);
        ctx.lineTo(lx, 24);
        ctx.fill();
      }
    });

    // beats / downbeats (биты рисуем только при достаточном зуме)
    if (beats && span < duration * 0.6) {
      ctx.strokeStyle = '#ffffff14';
      ctx.beginPath();
      for (const b of beats) {
        if (b < t0 || b > t1) continue;
        ctx.moveTo(tx(b), H - 14);
        ctx.lineTo(tx(b), H);
      }
      ctx.stroke();
    }
    if (downbeats) {
      ctx.strokeStyle = '#ffffff30';
      ctx.beginPath();
      for (const b of downbeats) {
        if (b < t0 || b > t1) continue;
        ctx.moveTo(tx(b), H - 26);
        ctx.lineTo(tx(b), H);
      }
      ctx.stroke();
      // каждые 4 такта — фразовая метка повыше и заметнее + номер группы
      ctx.strokeStyle = '#ffb84f55';
      ctx.beginPath();
      for (let i = 0; i < downbeats.length; i += 4) {
        const b = downbeats[i];
        if (b < t0 || b > t1) continue;
        ctx.moveTo(tx(b), H - 44);
        ctx.lineTo(tx(b), H);
      }
      ctx.stroke();
      // мелкая нумерация фразовых групп (1, 2, 3...) — при умеренном зуме,
      // чтобы цифры не слипались на полном обзоре длинного трека
      const groupPx = ((downbeats[4] || duration) - (downbeats[0] || 0)) / span * W;
      if (groupPx > 26) {
        ctx.fillStyle = '#ffb84f88';
        ctx.font = '9px "JetBrains Mono", monospace';
        for (let i = 0; i < downbeats.length; i += 4) {
          const b = downbeats[i];
          if (b < t0 || b > t1) continue;
          ctx.fillText(String(i / 4 + 1), tx(b) + 3, H - 34);
        }
      }
    }

    // waveform
    if (peaksRef.current) {
      const {
        peaks,
        W: PW
      } = peaksRef.current;
      ctx.strokeStyle = '#8fb0ec';
      ctx.globalAlpha = 0.85;
      ctx.beginPath();
      const mid = H / 2,
        amp = H / 2 - 10;
      for (let x = 0; x < W; x++) {
        const tt = t0 + x / W * span;
        const pi = Math.min(PW - 1, Math.floor(tt / duration * PW));
        ctx.moveTo(x + .5, mid + peaks[pi * 2] * amp);
        ctx.lineTo(x + .5, mid + peaks[pi * 2 + 1] * amp);
      }
      ctx.stroke();
      ctx.globalAlpha = 1;
    }

    // boundaries
    segments.forEach((s, i) => {
      if (i === 0 || s.start < t0 || s.start > t1) return;
      const x = tx(s.start);
      ctx.strokeStyle = '#ffffffcc';
      ctx.lineWidth = 2;
      ctx.beginPath();
      ctx.moveTo(x, 0);
      ctx.lineTo(x, H);
      ctx.stroke();
      ctx.lineWidth = 1;
      ctx.fillStyle = '#ffffffcc';
      ctx.beginPath();
      ctx.moveTo(x - 5, 0);
      ctx.lineTo(x + 5, 0);
      ctx.lineTo(x, 8);
      ctx.fill();
    });

    // labels + качество лупа
    segments.forEach((s, i) => {
      if (s.end < t0 || s.start > t1) return;
      const c = segColor(s, i);
      ctx.fillStyle = c;
      ctx.font = '600 11px Manrope, sans-serif';
      const lx = Math.max(tx(s.start) + 6, 6);
      ctx.fillText(s.label, lx, 15);
      if (s.loopability != null) {
        const q = s.loopability;
        ctx.fillStyle = q > 0.75 ? '#34d399' : q > 0.55 ? '#ffb84f' : '#fb6a6a';
        ctx.font = '600 10px "JetBrains Mono", monospace';
        ctx.fillText('\u27F3' + Math.round(q * 100) + '%', lx, 28);
      }
    });

    // скроллбар при зуме: дорожка + перетаскиваемый бегунок
    if (span < duration * 0.999) {
      const SB_H = 12;
      ctx.fillStyle = '#ffffff14';
      ctx.fillRect(0, H - SB_H, W, SB_H);
      const bx = t0 / duration * W;
      const bw = Math.max(24, span / duration * W);
      const hover = dragRef.current && dragRef.current.type === 'scroll';
      ctx.fillStyle = hover ? '#8aa8ff' : '#6a8dff';
      if (ctx.roundRect) {
        ctx.beginPath();
        ctx.roundRect(bx, H - SB_H + 2, bw, SB_H - 4, 4);
        ctx.fill();
      } else {
        ctx.fillRect(bx, H - SB_H + 2, bw, SB_H - 4);
      }
      // насечки на бегунке
      ctx.strokeStyle = '#0a0d14aa';
      ctx.beginPath();
      const cxm = bx + bw / 2;
      for (const dx of [-4, 0, 4]) {
        ctx.moveTo(cxm + dx, H - SB_H + 4);
        ctx.lineTo(cxm + dx, H - 4);
      }
      ctx.stroke();
    }

    // playhead (или позиция, выбранная до запуска / при перетаскивании)
    let pos = dragRef.current && dragRef.current.type === 'playhead' ? dragRef.current.pos : player && player.position();
    if (pos == null && player && player.pendingPos != null) pos = player.pendingPos;
    if (pos != null && pos >= t0 && pos <= t1) {
      const x = tx(pos);
      const grad = ctx.createLinearGradient(x - 8, 0, x + 8, 0);
      grad.addColorStop(0, 'rgba(52,211,153,0)');
      grad.addColorStop(.5, 'rgba(52,211,153,.25)');
      grad.addColorStop(1, 'rgba(52,211,153,0)');
      ctx.fillStyle = grad;
      ctx.fillRect(x - 8, 0, 16, H);
      ctx.strokeStyle = '#34d399';
      ctx.lineWidth = 2;
      ctx.beginPath();
      ctx.moveTo(x, 0);
      ctx.lineTo(x, H);
      ctx.stroke();
      // ручка плейхеда
      ctx.fillStyle = '#34d399';
      ctx.beginPath();
      ctx.arc(x, 6, 5, 0, Math.PI * 2);
      ctx.fill();
      ctx.lineWidth = 1;
    }
  }, [segments, beats, downbeats, duration, playingSeg, player]);
  useEffect(() => {
    let raf;
    const loop = () => {
      draw();
      raf = requestAnimationFrame(loop);
    };
    raf = requestAnimationFrame(loop);
    return () => cancelAnimationFrame(raf);
  }, [draw]);
  const timeAt = e => {
    const rect = canvasRef.current.getBoundingClientRect();
    const {
      t0,
      t1
    } = view();
    const tt = t0 + (e.clientX - rect.left) / rect.width * (t1 - t0);
    return Math.max(0, Math.min(duration, tt));
  };
  const tolTime = () => {
    const rect = canvasRef.current.getBoundingClientRect();
    const {
      t0,
      t1
    } = view();
    return 8 / rect.width * (t1 - t0);
  };
  const snapTime = tt => {
    if (!snap || !downbeats || !downbeats.length) return tt;
    let best = tt,
      bd = Infinity;
    for (const b of downbeats) {
      const d = Math.abs(b - tt);
      if (d < bd) {
        bd = d;
        best = b;
      }
    }
    const {
      t0,
      t1
    } = view();
    return bd < (t1 - t0) * 0.01 + 0.35 ? best : tt;
  };

  // wheel: зум к курсору; shift+wheel / горизонтальный скролл: панорама
  const onWheel = e => {
    if (!duration) return;
    e.preventDefault();
    const {
      t0,
      t1
    } = view();
    const span = t1 - t0;
    if (e.shiftKey || Math.abs(e.deltaX) > Math.abs(e.deltaY)) {
      const dt = (e.deltaX || e.deltaY) / 500 * span;
      let n0 = t0 + dt,
        n1 = t1 + dt;
      if (n0 < 0) {
        n1 -= n0;
        n0 = 0;
      }
      if (n1 > duration) {
        n0 -= n1 - duration;
        n1 = duration;
      }
      viewRef.current = {
        t0: Math.max(0, n0),
        t1: Math.min(duration, n1)
      };
      return;
    }
    const cursor = timeAt(e);
    const factor = e.deltaY > 0 ? 1.25 : 0.8;
    let ns = Math.min(duration, Math.max(2, span * factor));
    const ratio = (cursor - t0) / span;
    let n0 = cursor - ns * ratio,
      n1 = n0 + ns;
    if (n0 < 0) {
      n1 -= n0;
      n0 = 0;
    }
    if (n1 > duration) {
      n0 -= n1 - duration;
      n1 = duration;
    }
    viewRef.current = ns >= duration ? {
      t0: 0,
      t1: 0
    } : {
      t0: Math.max(0, n0),
      t1: n1
    };
  };
  const onMouseDown = e => {
    if (!duration) return;
    const tt = timeAt(e);
    const tolT = tolTime();
    // 0) скроллбар (нижние 12px при зуме)
    {
      const rect = canvasRef.current.getBoundingClientRect();
      const my = e.clientY - rect.top;
      const {
        t0,
        t1
      } = view();
      const span = t1 - t0;
      if (span < duration * 0.999 && my > H - 14) {
        const W = rect.width;
        const bx = t0 / duration * W;
        const bw = Math.max(24, span / duration * W);
        const mx = e.clientX - rect.left;
        if (mx >= bx && mx <= bx + bw) {
          // тащим бегунок
          dragRef.current = {
            type: 'scroll',
            grabDx: mx - bx,
            span
          };
        } else {
          // клик по дорожке — прыжок окна и сразу тащим
          let n0 = mx / W * duration - span / 2;
          n0 = Math.max(0, Math.min(duration - span, n0));
          viewRef.current = {
            t0: n0,
            t1: n0 + span
          };
          dragRef.current = {
            type: 'scroll',
            grabDx: bw / 2,
            span
          };
        }
        e.preventDefault();
        return;
      }
    }
    // 1) плейхед — приоритет
    const pos = (player && player.position()) ?? (player && player.pendingPos);
    if (pos != null && Math.abs(pos - tt) < tolT) {
      dragRef.current = {
        type: 'playhead',
        pos
      };
      e.preventDefault();
      return;
    }
    // 2) маркер loopStart
    for (let i = 0; i < segments.length; i++) {
      const s = segments[i];
      if (s.loop !== false && s.loopStart != null && Math.abs(s.loopStart - tt) < tolT) {
        dragRef.current = {
          type: 'loopstart',
          idx: i
        };
        if (beginEdit) beginEdit();
        e.preventDefault();
        return;
      }
    }
    // 3) границы сегментов
    for (let i = 1; i < segments.length; i++) {
      if (Math.abs(segments[i].start - tt) < tolT) {
        dragRef.current = {
          type: 'bound',
          idx: i
        };
        if (beginEdit) beginEdit();
        e.preventDefault();
        return;
      }
    }
    // 4) Alt+клик внутри части — установить loopStart в этой точке
    if (e.altKey) {
      const i = segments.findIndex(s => tt > s.start + 0.3 && tt < s.end - 0.3);
      if (i >= 0) {
        const nt = snapTime(tt);
        setSegments(segs => {
          const ns = segs.map(s => ({
            ...s
          }));
          ns[i].loopStart = Math.max(ns[i].start + 0.3, Math.min(ns[i].end - 0.5, nt));
          return ns;
        });
        return;
      }
    }
    // 5) клик по свободному месту — перемотка в эту точку
    player.seek(tt);
  };
  const onMouseMove = e => {
    const canvas = canvasRef.current;
    if (!canvas || !duration) return;
    const tt = timeAt(e);
    const d = dragRef.current;
    if (d && d.type === 'scroll') {
      const rect = canvas.getBoundingClientRect();
      const W = rect.width;
      const mx = e.clientX - rect.left;
      const span = d.span;
      let n0 = (mx - d.grabDx) / W * duration;
      n0 = Math.max(0, Math.min(duration - span, n0));
      viewRef.current = {
        t0: n0,
        t1: n0 + span
      };
      return;
    }
    if (d && d.type === 'playhead') {
      d.pos = Math.max(0, Math.min(duration - 0.05, tt));
      return;
    }
    if (d && d.type === 'loopstart') {
      const i = d.idx;
      const s = segments[i];
      const nt = Math.max(s.start + 0.3, Math.min(s.end - 0.5, snapTime(tt)));
      setSegments(segs => {
        const ns = segs.map(x => ({
          ...x
        }));
        ns[i].loopStart = nt;
        return ns;
      }, true);
      return;
    }
    if (d && d.type === 'bound') {
      const i = d.idx;
      const lo = segments[i - 1].start + 0.5;
      const hi = segments[i].end - 0.5;
      const nt = Math.max(lo, Math.min(hi, snapTime(tt)));
      setSegments(segs => {
        const ns = segs.map(s => ({
          ...s
        }));
        ns[i - 1].end = nt;
        ns[i].start = nt;
        return ns;
      }, true);
      return;
    }
    const tolT = tolTime();
    const rect2 = canvas.getBoundingClientRect();
    const my2 = e.clientY - rect2.top;
    const v2 = view();
    const onScrollbar = v2.t1 - v2.t0 < duration * 0.999 && my2 > H - 14;
    const pos = (player && player.position()) ?? (player && player.pendingPos);
    const onPlayhead = pos != null && Math.abs(pos - tt) < tolT;
    const onLoopStart = segments.some(s => s.loop !== false && s.loopStart != null && Math.abs(s.loopStart - tt) < tolT);
    const nearBound = segments.some((s, i) => i > 0 && Math.abs(s.start - tt) < tolT);
    canvas.style.cursor = onScrollbar ? 'grab' : onPlayhead ? 'grab' : onLoopStart || nearBound ? 'ew-resize' : 'pointer';
  };
  const onMouseUp = () => {
    const d = dragRef.current;
    dragRef.current = null;
    if (d && d.type === 'playhead') player.seek(d.pos);
    if (d && (d.type === 'bound' || d.type === 'loopstart') && commitEdit) commitEdit();
  };
  const onDblClick = e => {
    const tt = snapTime(timeAt(e));
    setSegments(segs => {
      const i = segs.findIndex(s => tt > s.start + 0.5 && tt < s.end - 0.5);
      if (i < 0) return segs;
      const ns = segs.map(s => ({
        ...s
      }));
      const right = {
        start: tt,
        end: ns[i].end,
        label: ns[i].label + '·2'
      };
      ns[i] = {
        ...ns[i],
        end: tt
      };
      ns.splice(i + 1, 0, right);
      return ns;
    });
  };
  useEffect(() => {
    window.addEventListener('mouseup', onMouseUp);
    const cv = canvasRef.current;
    if (cv) cv.addEventListener('wheel', onWheel, {
      passive: false
    });
    return () => {
      window.removeEventListener('mouseup', onMouseUp);
      if (cv) cv.removeEventListener('wheel', onWheel);
    };
  }, [duration, segments]);
  return /*#__PURE__*/React.createElement("div", {
    className: "canvas-wrap"
  }, /*#__PURE__*/React.createElement("canvas", {
    ref: canvasRef,
    style: {
      height: H
    },
    onMouseDown: onMouseDown,
    onMouseMove: onMouseMove,
    onDoubleClick: onDblClick
  }), aiWorking && /*#__PURE__*/React.createElement(AiOverlay, {
    t: t
  }), /*#__PURE__*/React.createElement("div", {
    className: "hint"
  }, t.wave_hint));
}

// Оверлей ИИ-обработки: сканирующая полоса + сменяющиеся стадии
function AiOverlay({
  t
}) {
  const stages = [t.ai_stage1, t.ai_stage2, t.ai_stage3, t.ai_stage4];
  const [idx, setIdx] = useState(0);
  useEffect(() => {
    // примерные длительности стадий (сек) при первом прогоне
    const timers = [setTimeout(() => setIdx(1), 8000), setTimeout(() => setIdx(2), 45000), setTimeout(() => setIdx(3), 70000)];
    return () => timers.forEach(clearTimeout);
  }, []);
  return /*#__PURE__*/React.createElement("div", {
    className: "ai-overlay"
  }, /*#__PURE__*/React.createElement("div", {
    className: "scanline"
  }), /*#__PURE__*/React.createElement("div", {
    className: "ai-bars"
  }, /*#__PURE__*/React.createElement("i", null), /*#__PURE__*/React.createElement("i", null), /*#__PURE__*/React.createElement("i", null), /*#__PURE__*/React.createElement("i", null), /*#__PURE__*/React.createElement("i", null), /*#__PURE__*/React.createElement("i", null), /*#__PURE__*/React.createElement("i", null)), /*#__PURE__*/React.createElement("div", {
    className: "ai-title"
  }, "\u2728 ", t.ai_working), /*#__PURE__*/React.createElement("div", {
    className: "ai-stage"
  }, stages[idx]));
}

// ================================ App ======================================
function App() {
  const [lang, setLang] = useState(() => {
    const saved = localStorage.getItem('musslop_lang');
    return STR[saved] ? saved : 'ru';
  });
  const t = STR[lang];
  const setLanguage = l => {
    setLang(l);
    localStorage.setItem('musslop_lang', l);
    document.documentElement.lang = l;
  };
  const [trackId, setTrackId] = useState(null);
  const [trackName, setTrackName] = useState('');
  const [loading, setLoading] = useState(null);
  const [error, setError] = useState(null);
  const [analysis, setAnalysis] = useState(null);
  const [segments, setSegmentsRaw] = useState([]);

  // --- Undo (Ctrl+Z): история изменений сегментов -------------------------
  const historyRef = useRef([]); // стек прошлых состояний
  const dragSnapRef = useRef(null); // снимок до начала drag-серии
  // обычное изменение: снимок в историю; silent=true — без записи (drag)
  const setSegments = useCallback((updater, silent = false) => {
    setSegmentsRaw(prev => {
      const next = typeof updater === 'function' ? updater(prev) : updater;
      if (!silent && next !== prev) {
        historyRef.current.push(prev);
        if (historyRef.current.length > 100) historyRef.current.shift();
      }
      return next;
    });
  }, []);
  // drag-серия: один undo-шаг на всё перетаскивание
  const beginEdit = useCallback(() => {
    setSegmentsRaw(prev => {
      dragSnapRef.current = prev;
      return prev;
    });
  }, []);
  const commitEdit = useCallback(() => {
    const snap0 = dragSnapRef.current;
    dragSnapRef.current = null;
    if (snap0 == null) return;
    setSegmentsRaw(prev => {
      if (prev !== snap0) {
        historyRef.current.push(snap0);
        if (historyRef.current.length > 100) historyRef.current.shift();
      }
      return prev;
    });
  }, []);
  const undo = useCallback(() => {
    const prev = historyRef.current.pop();
    if (prev) setSegmentsRaw(prev);
  }, []);
  const [buffer, setBuffer] = useState(null);
  const [snap, setSnap] = useState(true);
  const [nSeg, setNSeg] = useState('');
  const [aiWorking, setAiWorking] = useState(false); // ИИ-анализ в процессе
  const [exportOpen, setExportOpen] = useState(false);
  const [tailOn, setTailOn] = useState(true);
  const [bassSwapOn, setBassSwapOn] = useState(true);
  const [stinger, setStinger] = useState('none');
  const [volume, setVolumeState] = useState(() => {
    const v = parseFloat(localStorage.getItem('musslop_volume'));
    // сохранённый mute (0) не восстанавливаем: после перезагрузки страницы
    // «тихий» плеер выглядит как сломанный звук
    return isFinite(v) && v > 0.02 ? v : 1;
  });
  const setVolume = v => {
    setVolumeState(v);
    localStorage.setItem('musslop_volume', String(v));
    if (playerRef.current) playerRef.current.setVolume(v);
  };
  const [deepAvailable, setDeepAvailable] = useState(false);
  useEffect(() => {
    fetch('/api/health').then(r => r.json()).then(h => setDeepAvailable(!!h.deep_available)).catch(() => {});
  }, []);
  const [dragOver, setDragOver] = useState(false);
  const [crossfade, setCrossfade] = useState(0); // сек
  const [transMode, setTransMode] = useState('loop'); // 'loop' | 'phrase'
  const [phraseBars, setPhraseBars] = useState(4); // 4 или 8 тактов
  const [, force] = useState(0);
  const playerRef = useRef(null);
  const fileRef = useRef(null);
  const markupRef = useRef(null);
  const loopQT = useRef(null);
  if (!playerRef.current) {
    playerRef.current = new LoopPlayer();
    playerRef.current.volume = volume;
  }
  const player = playerRef.current;
  useEffect(() => {
    player.onState = () => force(x => x + 1);
  }, []);
  // стингеры: скачиваем сразу (байты), декодируем лениво — при первом
  // воспроизведении. НЕ создаём AudioContext без жеста пользователя:
  // авто-созданный suspended-контекст ломает звук в некоторых браузерах.
  const stingerRaw = useRef({});
  useEffect(() => {
    (async () => {
      for (const name of ['cymbal', 'boom', 'riser']) {
        try {
          stingerRaw.current[name] = await (await fetch(`stingers/${name}.wav`)).arrayBuffer();
        } catch (e) {}
      }
    })();
  }, []);
  useEffect(() => {
    player.loadStingers = async () => {
      if (!player.ctx) return;
      for (const [name, ab] of Object.entries(stingerRaw.current)) {
        if (!player.stingerBuffers[name] && ab) {
          try {
            player.stingerBuffers[name] = await player.ctx.decodeAudioData(ab.slice(0));
          } catch (e) {}
        }
      }
    };
  }, []);
  // смена трека -> стемы старого трека неактуальны
  useEffect(() => {
    player.stems = null;
    player.stemGains = null;
    setStemsState('none');
  }, [trackId]);
  useEffect(() => {
    player.setSegments(segments);
  }, [segments]);
  useEffect(() => {
    player.crossfade = crossfade;
  }, [crossfade]);
  useEffect(() => {
    player.transitionMode = transMode;
  }, [transMode]);
  useEffect(() => {
    player.phraseBars = phraseBars;
  }, [phraseBars]);
  useEffect(() => {
    if (analysis) player.downbeats = analysis.downbeats || [];
  }, [analysis]);
  useEffect(() => () => player.stop(false), []);

  // пересчёт качества лупа после ручного редактирования (debounce 800мс)
  useEffect(() => {
    if (!trackId || !segments.length) return;
    clearTimeout(loopQT.current);
    loopQT.current = setTimeout(async () => {
      try {
        const r = await fetch(`/api/loopability/${trackId}`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json'
          },
          body: JSON.stringify(segments.map(s => ({
            start: s.start,
            end: s.end
          })))
        });
        if (!r.ok) return;
        const {
          loopability
        } = await r.json();
        setSegments(segs => segs.length === loopability.length ? segs.map((s, i) => ({
          ...s,
          loopability: loopability[i]
        })) : segs);
      } catch (e) {}
    }, 800);
    return () => clearTimeout(loopQT.current);
  }, [trackId, segments.map(s => `${s.start.toFixed(2)}_${s.end.toFixed(2)}`).join('|')]);

  // --- Стемы (vertical layering) -------------------------------------------
  const [stemsState, setStemsState] = useState('none'); // none|loading|ready
  const [intensity, setIntensityState] = useState(1);
  const setIntensity = v => {
    setIntensityState(v);
    player.setIntensity(v);
  };
  const loadStems = async () => {
    if (!trackId || stemsState === 'loading') return;
    setStemsState('loading');
    setLoading(t.stems_loading);
    try {
      const r = await fetch(`/api/stems/${trackId}`, {
        method: 'POST'
      });
      if (!r.ok) throw new Error((await r.json()).detail || t.err_analyze);
      player._ensureCtx();
      const names = ['drums', 'bass', 'other', 'vocals'];
      const bufs = {};
      for (let i = 0; i < names.length; i++) {
        setLoading(`${t.stems_downloading} ${i + 1}/4…`);
        const ab = await (await fetch(`/api/stems/${trackId}/${names[i]}`)).arrayBuffer();
        bufs[names[i]] = await player.ctx.decodeAudioData(ab);
      }
      player.stems = bufs;
      player.stemGains = null; // пересоздать с текущей интенсивностью
      setStemsState('ready');
      // перезапустить воспроизведение на стемах с текущей позиции
      if (player.playing) {
        const pos = player.position();
        if (pos != null) player._softRestartAt(pos);
      }
    } catch (e) {
      setError(String(e.message || e));
      setStemsState('none');
    } finally {
      setLoading(null);
    }
  };
  const unloadStems = () => {
    player.stems = null;
    player.stemGains = null;
    setStemsState('none');
    if (player.playing) {
      const pos = player.position();
      if (pos != null) player._softRestartAt(pos);
    }
  };

  // --- Импорт по URL ---------------------------------------------------------
  const [importUrl, setImportUrl] = useState('');
  const importFromUrl = async () => {
    const url = importUrl.trim();
    if (!url) return;
    setError(null);
    setLoading(t.url_downloading);
    try {
      const r = await fetch('/api/import_url', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          url
        })
      });
      if (!r.ok) throw new Error((await r.json()).detail || t.err_upload);
      const {
        track_id,
        name
      } = await r.json();
      setImportUrl('');
      loadHistory();
      await openFromHistory({
        track_id,
        name
      });
    } catch (e) {
      setError(String(e.message || e));
    } finally {
      setLoading(null);
    }
  };
  const exportLoops = async () => {
    if (!trackId) return;
    setLoading(t.exporting);
    try {
      const r = await fetch(`/api/export/${trackId}`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(segments.map(s => ({
          start: s.start,
          end: s.end,
          label: s.label
        })))
      });
      if (!r.ok) throw new Error(t.err_export);
      // скачивание с прогрессом (zip может быть большим — полное качество WAV)
      const total = +r.headers.get('Content-Length') || 0;
      const reader = r.body.getReader();
      const chunks = [];
      let got = 0;
      while (true) {
        const {
          done,
          value
        } = await reader.read();
        if (done) break;
        chunks.push(value);
        got += value.length;
        setLoading(total ? `${t.export_downloading} ${Math.round(got / total * 100)}% (${(got / 1048576).toFixed(0)} MB)` : `${t.export_downloading} ${(got / 1048576).toFixed(0)} MB`);
      }
      const blob = new Blob(chunks, {
        type: 'application/zip'
      });
      const a = document.createElement('a');
      a.href = URL.createObjectURL(blob);
      a.download = (trackName || 'track').replace(/\.[^.]+$/, '') + '_loops.zip';
      a.click();
      URL.revokeObjectURL(a.href);
    } catch (e) {
      setError(String(e.message || e));
    } finally {
      setLoading(null);
    }
  };
  const exportMarkup = () => {
    const data = {
      track: trackName,
      tempo: analysis && analysis.tempo,
      segments
    };
    const blob = new Blob([JSON.stringify(data, null, 2)], {
      type: 'application/json'
    });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = (trackName || 'markup').replace(/\.[^.]+$/, '') + '.musslop.json';
    a.click();
    URL.revokeObjectURL(a.href);
  };
  const importMarkup = async file => {
    try {
      const data = JSON.parse(await file.text());
      if (!Array.isArray(data.segments) || !data.segments.length) throw new Error('no segments');
      const segs = data.segments.map(s => ({
        start: +s.start,
        end: +s.end,
        label: String(s.label || ''),
        loop: s.loop !== false,
        transition: !!s.transition,
        loopStart: isFinite(+s.loopStart) ? +s.loopStart : undefined
      })).filter(s => isFinite(s.start) && isFinite(s.end) && s.end > s.start).sort((a, b) => a.start - b.start);
      if (!segs.length) throw new Error('empty markup');
      setSegments(segs);
      setError(null);
    } catch (e) {
      setError(t.err_markup + ' ' + e.message);
    } finally {
      if (markupRef.current) markupRef.current.value = '';
    }
  };
  const upload = async file => {
    setError(null);
    player.stop();
    try {
      // Файл уже у браузера — декодируем его напрямую, без скачивания с сервера.
      // Параллельно отправляем на сервер для анализа структуры.
      setLoading(t.loading_decode);
      const fd = new FormData();
      fd.append('file', file);
      const uploadPromise = fetch('/api/upload', {
        method: 'POST',
        body: fd
      });
      const ab = await file.arrayBuffer();
      player._ensureCtx();
      let buf = null;
      try {
        buf = await player.ctx.decodeAudioData(ab.slice(0));
      } catch (e) {
        buf = null;
      }
      setLoading(t.loading_upload);
      const r = await uploadPromise;
      if (!r.ok) throw new Error((await r.json()).detail || t.err_upload);
      const {
        track_id,
        name
      } = await r.json();
      setTrackId(track_id);
      setTrackName(name);

      // Анализ на сервере — источник истины о длительности
      const a = await doAnalyze(track_id, null);
      loadHistory();

      // сверяем длительности: браузерные декодеры иногда обрезают
      // FLAC/m4a с вложенной обложкой — тогда берём WAV с сервера
      const serverDur = a ? a.duration : null;
      const durOk = buf && serverDur != null && Math.abs(buf.duration - serverDur) < Math.max(1, serverDur * 0.02);
      if (buf && (serverDur == null || durOk)) {
        player.buffer = buf;
        setBuffer(buf);
      } else {
        setLoading(t.loading_transcode);
        const wavR = await fetch(`/api/audio/${track_id}?transcode=1`);
        if (!wavR.ok) throw new Error(t.err_upload);
        const wavAb = await wavR.arrayBuffer();
        const wavBuf = await player.ctx.decodeAudioData(wavAb);
        player.buffer = wavBuf;
        setBuffer(wavBuf);
      }
    } catch (e) {
      setError(String(e.message || e));
    } finally {
      setLoading(null);
    }
  };

  // --- История треков ------------------------------------------------------
  const [history, setHistory] = useState([]);
  const loadHistory = useCallback(async () => {
    try {
      const r = await fetch('/api/tracks');
      if (r.ok) setHistory((await r.json()).tracks);
    } catch (e) {}
  }, []);
  useEffect(() => {
    loadHistory();
  }, []);

  // автосохранение разметки на сервер (debounce 1.2с)
  const saveT = useRef(null);
  useEffect(() => {
    if (!trackId || !analysis || !segments.length) return;
    clearTimeout(saveT.current);
    saveT.current = setTimeout(() => {
      fetch(`/api/markup/${trackId}`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          duration: analysis.duration,
          tempo: analysis.tempo,
          beats: analysis.beats,
          downbeats: analysis.downbeats,
          n_suggested: analysis.n_suggested,
          n_max: analysis.n_max,
          segments
        })
      }).catch(() => {});
    }, 1200);
    return () => clearTimeout(saveT.current);
  }, [trackId, segments, analysis]);

  // открыть трек из истории: аудио с сервера + сохранённая разметка
  const openFromHistory = async item => {
    setError(null);
    player.stop();
    try {
      setLoading(t.loading_history);
      const [audioR, markupR] = await Promise.all([fetch(`/api/audio/${item.track_id}`), fetch(`/api/markup/${item.track_id}`)]);
      if (!audioR.ok) throw new Error(t.err_upload);
      const ab = await audioR.arrayBuffer();
      player._ensureCtx();
      let buf = null;
      try {
        buf = await player.ctx.decodeAudioData(ab);
      } catch (e) {
        buf = null;
      }
      setTrackId(item.track_id);
      setTrackName(item.name);
      const markup = markupR.ok ? (await markupR.json()).markup : null;
      let serverDur = markup ? markup.duration : null;
      let analyzed = null;
      if (markup && Array.isArray(markup.segments) && markup.segments.length) {
        historyRef.current = [];
        setAnalysis({
          duration: markup.duration,
          tempo: markup.tempo || 0,
          beats: markup.beats || [],
          downbeats: markup.downbeats || [],
          n_suggested: markup.n_suggested,
          n_max: markup.n_max,
          segments: markup.segments,
          fallback: false
        });
        setSegmentsRaw(markup.segments);
      } else {
        analyzed = await doAnalyze(item.track_id, null);
        if (analyzed) serverDur = analyzed.duration;
      }

      // браузер мог обрезать оригинал (FLAC с обложкой и т.п.)
      const durOk = buf && serverDur != null && Math.abs(buf.duration - serverDur) < Math.max(1, serverDur * 0.02);
      if (buf && (serverDur == null || durOk)) {
        player.buffer = buf;
        setBuffer(buf);
      } else {
        setLoading(t.loading_transcode);
        const wavR = await fetch(`/api/audio/${item.track_id}?transcode=1`);
        if (!wavR.ok) throw new Error(t.err_upload);
        const wavBuf = await player.ctx.decodeAudioData(await wavR.arrayBuffer());
        player.buffer = wavBuf;
        setBuffer(wavBuf);
      }
    } catch (e) {
      setError(String(e.message || e));
    } finally {
      setLoading(null);
    }
  };
  const deleteFromHistory = async (e, item) => {
    e.stopPropagation();
    try {
      await fetch(`/api/tracks/${item.track_id}`, {
        method: 'DELETE'
      });
      loadHistory();
    } catch (er) {}
  };
  const toggleFavorite = async (e, item) => {
    if (e) e.stopPropagation();
    try {
      await fetch(`/api/favorite/${item.track_id}`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          favorite: !item.favorite
        })
      });
      loadHistory();
    } catch (er) {}
  };
  const currentFav = history.find(h => h.track_id === trackId);
  const doAnalyze = async (id, n, eng) => {
    const useEngine = eng || 'fast';
    const isDeep = useEngine === 'deep';
    setLoading(isDeep ? t.loading_deep : t.loading_analyze);
    if (isDeep) setAiWorking(true);
    try {
      const params = new URLSearchParams();
      if (n) params.set('n_segments', n);
      if (isDeep) params.set('engine', 'deep');
      const qs = params.toString();
      const r = await fetch(`/api/analyze/${id}${qs ? '?' + qs : ''}`);
      if (!r.ok) throw new Error((await r.json()).detail || t.err_analyze);
      const a = await r.json();
      setAnalysis(a);
      setSegments(a.segments);
      return a;
    } catch (e) {
      setError(String(e.message || e));
      return null;
    } finally {
      setLoading(null);
      setAiWorking(false);
    }
  };
  const onDrop = e => {
    e.preventDefault();
    setDragOver(false);
    const f = e.dataTransfer.files[0];
    if (f) upload(f);
  };
  const removeSeg = i => {
    if (segments.length <= 1) return;
    setSegments(segs => {
      const ns = segs.map(s => ({
        ...s
      }));
      if (i === 0) {
        ns[1].start = ns[0].start;
      } else {
        ns[i - 1].end = ns[i].end;
      }
      ns.splice(i, 1);
      return ns;
    });
  };

  // Разрезать часть в точке pos (сек); привязка к ближайшему downbeat
  const splitAt = pos => {
    if (pos == null || !analysis) return;
    let tt = pos;
    const dbs = analysis.downbeats || [];
    if (dbs.length) {
      let best = tt,
        bd = Infinity;
      for (const b of dbs) {
        const d = Math.abs(b - tt);
        if (d < bd) {
          bd = d;
          best = b;
        }
      }
      if (bd < 2.5) tt = best;
    }
    setSegments(segs => {
      const i = segs.findIndex(s => tt > s.start + 0.5 && tt < s.end - 0.5);
      if (i < 0) return segs;
      const ns = segs.map(s => ({
        ...s
      }));
      const right = {
        start: tt,
        end: ns[i].end,
        label: ns[i].label + '·2'
      };
      ns[i] = {
        ...ns[i],
        end: tt
      };
      ns.splice(i + 1, 0, right);
      return ns;
    });
  };

  // Разрезать в текущей позиции (играет / выбрана кликом), иначе — середина выбранной части
  const splitAtPlayhead = () => {
    let pos = player.position();
    if (pos == null) pos = player.pendingPos;
    if (pos == null && segments[player.segIndex]) {
      const s = segments[player.segIndex];
      pos = (s.start + s.end) / 2;
    }
    splitAt(pos);
  };

  // Разрезать конкретную часть пополам (по ближайшему такту к середине)
  const splitSeg = i => {
    const s = segments[i];
    if (!s) return;
    splitAt((s.start + s.end) / 2);
  };
  const playingSeg = player.playing ? player.segIndex : -1;
  const duration = analysis ? analysis.duration : 0;
  const splitRef = useRef(splitAtPlayhead);
  splitRef.current = splitAtPlayhead;
  useEffect(() => {
    const h = e => {
      if ((e.ctrlKey || e.metaKey) && e.code === 'KeyZ') {
        e.preventDefault();
        undo();
        return;
      }
      if (e.target.tagName === 'INPUT') return;
      if (e.code === 'Space') {
        e.preventDefault();
        player.playing ? player.stop() : player.play();
      }
      if (e.code === 'ArrowRight' || e.code === 'Enter') {
        e.preventDefault();
        player.advance();
      }
      if (e.code === 'KeyS') {
        e.preventDefault();
        splitRef.current();
      }
    };
    window.addEventListener('keydown', h);
    return () => window.removeEventListener('keydown', h);
  }, []);
  return /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("header", null, /*#__PURE__*/React.createElement("div", {
    className: "logo"
  }, /*#__PURE__*/React.createElement("h1", null, "MUSSLOP"), /*#__PURE__*/React.createElement("div", {
    className: "sub"
  }, t.tagline)), /*#__PURE__*/React.createElement("div", {
    className: "lang-switch"
  }, /*#__PURE__*/React.createElement("button", {
    className: lang === 'ru' ? 'on' : '',
    onClick: () => setLanguage('ru')
  }, "RU"), /*#__PURE__*/React.createElement("button", {
    className: lang === 'en' ? 'on' : '',
    onClick: () => setLanguage('en')
  }, "EN"), /*#__PURE__*/React.createElement("button", {
    className: lang === 'zh' ? 'on' : '',
    onClick: () => setLanguage('zh')
  }, "\u4E2D\u6587"))), /*#__PURE__*/React.createElement("div", {
    className: "panel"
  }, /*#__PURE__*/React.createElement("div", {
    className: "panel-title"
  }, t.upload_title), /*#__PURE__*/React.createElement("div", {
    className: 'dropzone' + (dragOver ? ' over' : ''),
    onClick: () => fileRef.current.click(),
    onDragOver: e => {
      e.preventDefault();
      setDragOver(true);
    },
    onDragLeave: () => setDragOver(false),
    onDrop: onDrop
  }, /*#__PURE__*/React.createElement("span", {
    className: "dz-icon"
  }, "\u266B"), trackName ? /*#__PURE__*/React.createElement("span", null, t.track, " ", /*#__PURE__*/React.createElement("b", null, trackName), " ", t.drop_replace) : /*#__PURE__*/React.createElement("span", null, t.drop_hint, /*#__PURE__*/React.createElement("br", null), /*#__PURE__*/React.createElement("span", {
    style: {
      fontSize: 12,
      opacity: .7
    }
  }, t.drop_formats)), /*#__PURE__*/React.createElement("input", {
    ref: fileRef,
    type: "file",
    accept: "audio/*",
    style: {
      display: 'none'
    },
    onChange: e => e.target.files[0] && upload(e.target.files[0])
  })), /*#__PURE__*/React.createElement("div", {
    className: "row",
    style: {
      marginTop: 10
    }
  }, /*#__PURE__*/React.createElement("input", {
    type: "text",
    placeholder: t.url_placeholder,
    value: importUrl,
    onChange: e => setImportUrl(e.target.value),
    onKeyDown: e => e.key === 'Enter' && importFromUrl(),
    style: {
      flex: 1,
      minWidth: 200,
      background: 'var(--panel2)',
      color: 'var(--text)',
      border: '1px solid var(--border)',
      borderRadius: 10,
      padding: '9px 12px',
      fontSize: 13.5,
      fontFamily: 'inherit',
      outline: 'none'
    }
  }), /*#__PURE__*/React.createElement("button", {
    onClick: importFromUrl,
    disabled: !importUrl.trim() || !!loading
  }, "\uD83D\uDD17 ", t.url_btn)), loading && /*#__PURE__*/React.createElement("div", {
    className: "status",
    style: {
      marginTop: 12
    }
  }, /*#__PURE__*/React.createElement("div", {
    className: "spinner"
  }), loading), error && /*#__PURE__*/React.createElement("div", {
    className: "error-box"
  }, t.err_prefix, " ", error), history.length > 0 && /*#__PURE__*/React.createElement("div", {
    style: {
      marginTop: 14
    }
  }, [{
    key: 'lib',
    title: t.library_title,
    items: history.filter(h => h.favorite)
  }, {
    key: 'hist',
    title: t.history_title,
    items: history.filter(h => !h.favorite)
  }].map(group => group.items.length > 0 && /*#__PURE__*/React.createElement("div", {
    key: group.key,
    style: {
      marginBottom: 10
    }
  }, /*#__PURE__*/React.createElement("div", {
    className: "panel-title",
    style: {
      marginBottom: 8
    }
  }, group.title), /*#__PURE__*/React.createElement("div", {
    className: "seg-list",
    style: {
      marginTop: 0
    }
  }, group.items.map(item => /*#__PURE__*/React.createElement("div", {
    key: item.track_id,
    className: 'seg-chip' + (item.track_id === trackId ? ' active' : ''),
    onClick: () => openFromHistory(item),
    title: t.history_open_tip
  }, /*#__PURE__*/React.createElement("span", {
    className: "x",
    style: {
      color: item.favorite ? '#ffb84f' : 'var(--muted)',
      fontSize: 14
    },
    title: item.favorite ? t.fav_remove_tip : t.fav_add_tip,
    onClick: e => toggleFavorite(e, item)
  }, item.favorite ? '★' : '☆'), /*#__PURE__*/React.createElement("span", {
    style: {
      fontSize: 13
    }
  }, item.has_markup ? '💾' : '♫'), /*#__PURE__*/React.createElement("span", {
    style: {
      fontWeight: 600,
      maxWidth: 220,
      overflow: 'hidden',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap'
    }
  }, item.name), item.duration != null && /*#__PURE__*/React.createElement("span", {
    className: "time"
  }, fmt(item.duration)), item.n_segments > 0 && /*#__PURE__*/React.createElement("span", {
    className: "time"
  }, item.n_segments, " ", t.history_parts), /*#__PURE__*/React.createElement("span", {
    className: "x",
    title: t.history_del_tip,
    onClick: e => deleteFromHistory(e, item)
  }, "\u2715")))))))), analysis && /*#__PURE__*/React.createElement("div", {
    className: "panel"
  }, /*#__PURE__*/React.createElement("div", {
    className: "panel-title"
  }, t.structure_title), /*#__PURE__*/React.createElement("div", {
    className: "row between",
    style: {
      marginBottom: 10
    }
  }, /*#__PURE__*/React.createElement("div", {
    className: "row"
  }, /*#__PURE__*/React.createElement("span", {
    className: "badge"
  }, t.tempo, " ", /*#__PURE__*/React.createElement("b", null, analysis.tempo.toFixed(1), " BPM")), /*#__PURE__*/React.createElement("span", {
    className: "badge"
  }, t.duration, " ", /*#__PURE__*/React.createElement("b", null, fmt(duration))), /*#__PURE__*/React.createElement("span", {
    className: "badge"
  }, t.parts, " ", /*#__PURE__*/React.createElement("b", null, segments.length), analysis.n_suggested != null && /*#__PURE__*/React.createElement("span", {
    style: {
      marginLeft: 6
    }
  }, "\xB7 ", t.n_suggested, " ", /*#__PURE__*/React.createElement("b", null, analysis.n_suggested), " \xB7 ", t.n_max, " ", /*#__PURE__*/React.createElement("b", null, analysis.n_max))), analysis.fallback && /*#__PURE__*/React.createElement("span", {
    className: "badge",
    style: {
      color: 'var(--danger)'
    }
  }, t.fallback)), /*#__PURE__*/React.createElement("div", {
    className: "row"
  }, /*#__PURE__*/React.createElement("input", {
    type: "number",
    min: "2",
    max: "24",
    placeholder: t.n_parts_ph,
    value: nSeg,
    onChange: e => setNSeg(e.target.value),
    title: t.n_parts_tip
  }), /*#__PURE__*/React.createElement("button", {
    onClick: () => doAnalyze(trackId, nSeg ? +nSeg : null),
    disabled: !!loading
  }, t.reanalyze), deepAvailable && /*#__PURE__*/React.createElement("button", {
    className: "ai-btn",
    onClick: () => doAnalyze(trackId, null, 'deep'),
    disabled: !!loading,
    title: t.engine_tip
  }, "\u2728 ", t.ai_split_btn))), /*#__PURE__*/React.createElement("div", {
    className: "row between",
    style: {
      marginBottom: 12
    }
  }, /*#__PURE__*/React.createElement("div", {
    className: "row"
  }, /*#__PURE__*/React.createElement("button", {
    onClick: splitAtPlayhead,
    title: t.split_tip
  }, t.split_btn), /*#__PURE__*/React.createElement("label", {
    className: "chk"
  }, /*#__PURE__*/React.createElement("input", {
    type: "checkbox",
    checked: snap,
    onChange: e => setSnap(e.target.checked)
  }), t.snap)), /*#__PURE__*/React.createElement("div", {
    className: "row"
  }, /*#__PURE__*/React.createElement("button", {
    onClick: () => currentFav && toggleFavorite(null, currentFav),
    disabled: !currentFav,
    title: currentFav && currentFav.favorite ? t.fav_remove_tip : t.fav_add_tip,
    style: currentFav && currentFav.favorite ? {
      color: '#ffb84f',
      borderColor: '#ffb84f66'
    } : {}
  }, currentFav && currentFav.favorite ? '★ ' + t.fav_in_lib : '☆ ' + t.fav_btn), /*#__PURE__*/React.createElement("div", {
    className: "dropdown"
  }, /*#__PURE__*/React.createElement("button", {
    className: "ghost",
    onClick: () => setExportOpen(o => !o)
  }, t.files_menu, " \u25BE"), exportOpen && /*#__PURE__*/React.createElement("div", {
    className: "dropdown-menu",
    onClick: () => setExportOpen(false)
  }, /*#__PURE__*/React.createElement("div", {
    className: "dropdown-item",
    onClick: exportLoops
  }, t.export_loops), /*#__PURE__*/React.createElement("div", {
    className: "dropdown-item",
    onClick: exportMarkup
  }, t.export_markup), /*#__PURE__*/React.createElement("div", {
    className: "dropdown-item",
    onClick: () => markupRef.current.click()
  }, t.import_markup))), /*#__PURE__*/React.createElement("input", {
    ref: markupRef,
    type: "file",
    accept: ".json",
    style: {
      display: 'none'
    },
    onChange: e => e.target.files[0] && importMarkup(e.target.files[0])
  }))), /*#__PURE__*/React.createElement(Waveform, {
    buffer: buffer,
    segments: segments,
    setSegments: setSegments,
    beats: analysis.beats,
    downbeats: analysis.downbeats,
    snap: snap,
    player: player,
    playingSeg: playingSeg,
    duration: duration,
    t: t,
    onSeekSeg: i => player.playing ? player.play(i) : (player.segIndex = i, force(x => x + 1)),
    beginEdit: beginEdit,
    commitEdit: commitEdit,
    aiWorking: aiWorking
  }), /*#__PURE__*/React.createElement("div", {
    className: "seg-list"
  }, segments.map((s, i) => {
    const gi = s.group ? s.group.charCodeAt(0) - 65 : i;
    const col = SEG_COLORS[gi % SEG_COLORS.length];
    const q = s.loopability;
    const qc = q == null ? 'var(--muted)' : q > 0.75 ? '#34d399' : q > 0.55 ? '#ffb84f' : '#fb6a6a';
    return /*#__PURE__*/React.createElement("div", {
      key: i,
      className: 'seg-chip' + (i === player.segIndex ? ' active' : ''),
      onClick: () => player.playing ? player.play(i) : (player.segIndex = i, force(x => x + 1))
    }, /*#__PURE__*/React.createElement("div", {
      className: "dot",
      style: {
        background: col
      }
    }), /*#__PURE__*/React.createElement("input", {
      value: s.label,
      onClick: e => e.stopPropagation(),
      onChange: e => setSegments(segs => {
        const ns = segs.map(x => ({
          ...x
        }));
        ns[i].label = e.target.value;
        return ns;
      })
    }), /*#__PURE__*/React.createElement("span", {
      className: "time"
    }, fmt(s.start), "\u2013", fmt(s.end)), q != null && /*#__PURE__*/React.createElement("span", {
      className: "time",
      title: t.loop_quality_tip,
      style: {
        color: qc
      }
    }, "\u27F3", Math.round(q * 100), "%"), /*#__PURE__*/React.createElement("span", {
      className: "x",
      title: t.loop_toggle_tip,
      style: {
        color: s.loop === false ? 'var(--danger)' : 'var(--accent2)'
      },
      onClick: e => {
        e.stopPropagation();
        setSegments(segs => {
          const ns = segs.map(x => ({
            ...x
          }));
          ns[i].loop = ns[i].loop === false;
          ns[i].transition = !ns[i].loop;
          return ns;
        });
      }
    }, s.loop === false ? '→' : '⟳'), s.loop === false && /*#__PURE__*/React.createElement("span", {
      className: "time",
      style: {
        color: 'var(--danger)'
      }
    }, t.transition_badge), /*#__PURE__*/React.createElement("span", {
      className: "x",
      title: t.split_seg_tip,
      onClick: e => {
        e.stopPropagation();
        splitSeg(i);
      }
    }, "\u2702"), /*#__PURE__*/React.createElement("span", {
      className: "x",
      title: t.del_seg,
      onClick: e => {
        e.stopPropagation();
        removeSeg(i);
      }
    }, "\u2715"));
  }))), analysis && /*#__PURE__*/React.createElement("div", {
    className: "panel"
  }, /*#__PURE__*/React.createElement("div", {
    className: "panel-title"
  }, t.player_title), /*#__PURE__*/React.createElement("div", {
    className: "row between"
  }, /*#__PURE__*/React.createElement("div", {
    className: "row"
  }, !player.playing ? /*#__PURE__*/React.createElement("button", {
    className: "primary",
    onClick: () => player.play()
  }, t.play) : /*#__PURE__*/React.createElement("button", {
    onClick: () => player.stop()
  }, t.stop), /*#__PURE__*/React.createElement("button", {
    className: 'go' + (player.advanceArmed ? ' armed' : ''),
    disabled: !player.playing || player.segIndex >= segments.length - 1,
    onClick: () => player.advance()
  }, player.advanceArmed ? t.next_armed : t.next)), /*#__PURE__*/React.createElement("div", {
    className: "now"
  }, player.playing && /*#__PURE__*/React.createElement("span", {
    className: "eq"
  }, /*#__PURE__*/React.createElement("i", null), /*#__PURE__*/React.createElement("i", null), /*#__PURE__*/React.createElement("i", null)), player.playing ? /*#__PURE__*/React.createElement("span", null, t.playing, " ", /*#__PURE__*/React.createElement("b", null, segments[player.segIndex] ? segments[player.segIndex].label : '–'), "\xA0\xB7 ", t.pass, player.loopCount, t.pass_suffix || '', player.advanceArmed && ' ' + t.transition_planned) : /*#__PURE__*/React.createElement("span", null, t.selected, " ", /*#__PURE__*/React.createElement("b", null, segments[player.segIndex] ? segments[player.segIndex].label : '–')))), /*#__PURE__*/React.createElement("div", {
    className: "row",
    style: {
      marginTop: 12
    }
  }, /*#__PURE__*/React.createElement("span", {
    className: "badge"
  }, t.trans_mode), /*#__PURE__*/React.createElement("div", {
    className: "lang-switch"
  }, /*#__PURE__*/React.createElement("button", {
    className: transMode === 'loop' ? 'on' : '',
    onClick: () => setTransMode('loop'),
    title: t.mode_loop_tip
  }, t.mode_loop), /*#__PURE__*/React.createElement("button", {
    className: transMode === 'phrase' ? 'on' : '',
    onClick: () => setTransMode('phrase'),
    title: t.mode_phrase_tip
  }, t.mode_phrase)), transMode === 'phrase' && /*#__PURE__*/React.createElement("div", {
    className: "lang-switch",
    title: t.phrase_len_tip
  }, /*#__PURE__*/React.createElement("button", {
    className: phraseBars === 4 ? 'on' : '',
    onClick: () => setPhraseBars(4)
  }, "4 ", t.bars), /*#__PURE__*/React.createElement("button", {
    className: phraseBars === 8 ? 'on' : '',
    onClick: () => setPhraseBars(8)
  }, "8 ", t.bars)), /*#__PURE__*/React.createElement("span", {
    className: "badge",
    style: {
      marginLeft: 12
    }
  }, t.crossfade), /*#__PURE__*/React.createElement("input", {
    type: "range",
    min: "0",
    max: "2",
    step: "0.1",
    value: crossfade,
    style: {
      width: 130,
      accentColor: 'var(--accent)'
    },
    onChange: e => setCrossfade(+e.target.value)
  }), /*#__PURE__*/React.createElement("span", {
    className: "time",
    style: {
      fontFamily: '"JetBrains Mono", monospace',
      fontSize: 12,
      color: 'var(--muted)'
    }
  }, crossfade.toFixed(1), "s")), /*#__PURE__*/React.createElement("div", {
    className: "row",
    style: {
      marginTop: 10
    }
  }, /*#__PURE__*/React.createElement("label", {
    className: "chk",
    title: t.tail_tip
  }, /*#__PURE__*/React.createElement("input", {
    type: "checkbox",
    checked: tailOn,
    onChange: e => {
      setTailOn(e.target.checked);
      player.tailEnabled = e.target.checked;
    }
  }), t.tail_label), /*#__PURE__*/React.createElement("label", {
    className: "chk",
    title: t.bass_swap_tip
  }, /*#__PURE__*/React.createElement("input", {
    type: "checkbox",
    checked: bassSwapOn,
    onChange: e => {
      setBassSwapOn(e.target.checked);
      player.bassSwap = e.target.checked;
    }
  }), t.bass_swap_label), /*#__PURE__*/React.createElement("span", {
    className: "badge",
    style: {
      marginLeft: 12
    },
    title: t.stinger_tip
  }, t.stinger_label), /*#__PURE__*/React.createElement("div", {
    className: "lang-switch"
  }, ['none', 'cymbal', 'boom', 'riser'].map(sg => /*#__PURE__*/React.createElement("button", {
    key: sg,
    className: stinger === sg ? 'on' : '',
    onClick: () => {
      setStinger(sg);
      player.stinger = sg;
    }
  }, t['stinger_' + sg])))), deepAvailable && /*#__PURE__*/React.createElement("div", {
    className: "row",
    style: {
      marginTop: 10
    }
  }, /*#__PURE__*/React.createElement("span", {
    className: "badge",
    title: t.stems_tip
  }, t.stems_label), stemsState !== 'ready' ? /*#__PURE__*/React.createElement("button", {
    className: "ai-btn",
    onClick: loadStems,
    disabled: stemsState === 'loading' || !!loading
  }, "\uD83C\uDF9A ", stemsState === 'loading' ? t.stems_working : t.stems_btn) : /*#__PURE__*/React.createElement(React.Fragment, null, /*#__PURE__*/React.createElement("span", {
    className: "badge",
    style: {
      color: 'var(--accent2)'
    }
  }, "\u2713 ", t.stems_ready), /*#__PURE__*/React.createElement("span", {
    className: "badge"
  }, t.intensity_label), /*#__PURE__*/React.createElement("input", {
    type: "range",
    min: "0",
    max: "1",
    step: "0.01",
    value: intensity,
    style: {
      width: 160,
      accentColor: '#a06bff'
    },
    onChange: e => setIntensity(+e.target.value)
  }), /*#__PURE__*/React.createElement("span", {
    className: "time",
    style: {
      fontFamily: '"JetBrains Mono", monospace',
      fontSize: 12,
      color: 'var(--muted)'
    }
  }, intensity < 0.25 ? t.int_calm : intensity < 0.5 ? t.int_low : intensity < 0.75 ? t.int_mid : t.int_full), /*#__PURE__*/React.createElement("button", {
    className: "ghost",
    onClick: unloadStems
  }, t.stems_off))), /*#__PURE__*/React.createElement("div", {
    className: "hint"
  }, t.keys_hint)), /*#__PURE__*/React.createElement("footer", null, t.footer, " \xB7 ", /*#__PURE__*/React.createElement("a", {
    href: "https://github.com/Siziff/musslop",
    target: "_blank"
  }, "GitHub")), /*#__PURE__*/React.createElement("div", {
    className: "volume-box",
    title: t.volume_tip
  }, /*#__PURE__*/React.createElement("span", {
    className: "vol-icon",
    onClick: () => setVolume(volume > 0 ? 0 : 1)
  }, volume === 0 ? '🔇' : volume < 0.5 ? '🔉' : '🔊'), /*#__PURE__*/React.createElement("input", {
    type: "range",
    min: "0",
    max: "1",
    step: "0.01",
    value: volume,
    onChange: e => setVolume(+e.target.value)
  }), /*#__PURE__*/React.createElement("span", {
    className: "vol-num"
  }, Math.round(volume * 100), "%"), /*#__PURE__*/React.createElement("span", {
    className: "vol-icon",
    title: t.beep_tip,
    onClick: () => {
      // тест-бип напрямую в destination, минуя master/стемы/фильтры
      player._ensureCtx();
      const o = player.ctx.createOscillator();
      const g = player.ctx.createGain();
      g.gain.value = 0.25;
      o.frequency.value = 660;
      o.connect(g);
      g.connect(player.ctx.destination);
      o.start();
      o.stop(player.ctx.currentTime + 0.25);
      setTimeout(() => force(x => x + 1), 300);
    }
  }, "\u266A?"), player.ctx && player.ctx.state !== 'running' && /*#__PURE__*/React.createElement("span", {
    className: "vol-num",
    style: {
      color: 'var(--danger)',
      width: 'auto'
    }
  }, player.ctx.state)));
}
ReactDOM.createRoot(document.getElementById('root')).render(/*#__PURE__*/React.createElement(App, null));