#!/usr/bin/env python3
"""Прекомпиляция JSX -> JS, чтобы не грузить Babel (2.9 MB) в браузер.

Берёт inline-скрипт type="text/babel" из frontend/index.html, компилирует
его Babel'ом (vendor/babel.min.js через quickjs) и пишет frontend/app.js.
Также генерирует frontend/index.html из index.src.html не требуется:
index.html остаётся исходником (dev-режим), сервер отдаёт index.prod.html
если он свежее. Запускать после каждого изменения index.html:

    python3 tools/build.py
"""
from __future__ import annotations

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FRONT = os.path.join(ROOT, "frontend")


def main() -> None:
    src_path = os.path.join(FRONT, "index.html")
    html = open(src_path, encoding="utf-8").read()

    m = re.search(r'<script type="text/babel"[^>]*>(.*?)</script>', html, re.S)
    if not m:
        sys.exit("index.html: не найден <script type=\"text/babel\">")
    jsx = m.group(1)

    import quickjs
    babel_src = open(os.path.join(FRONT, "vendor", "babel.min.js"),
                     encoding="utf-8").read()
    ctx = quickjs.Context()
    ctx.set_max_stack_size(256 * 1024 * 1024)
    ctx.eval("var console={log:function(){},warn:function(){},error:function(){}};"
             "var self=this; var window=this;")
    ctx.eval(babel_src)
    ctx.set("SRC", jsx)
    ctx.eval("var OUT = Babel.transform(SRC, {presets: ['react']}).code;")
    compiled = ctx.get("OUT")

    with open(os.path.join(FRONT, "app.js"), "w", encoding="utf-8") as f:
        f.write("/* autogenerated by tools/build.py — не редактировать */\n")
        f.write(compiled)

    # prod-вариант страницы: без babel и без inline-JSX;
    # хэш в query — иначе браузер кэширует старый app.js и «теряются» фичи
    import hashlib
    h = hashlib.md5(compiled.encode()).hexdigest()[:10]
    prod = html.replace('<script src="vendor/babel.min.js"></script>\n', "")
    prod = prod.replace(m.group(0), f'<script defer src="app.js?v={h}"></script>')
    with open(os.path.join(FRONT, "index.prod.html"), "w", encoding="utf-8") as f:
        f.write(prod)

    print(f"OK: app.js ({len(compiled)//1024} KB), index.prod.html")


if __name__ == "__main__":
    main()
