#!/usr/bin/env python3
"""Precompile JSX -> JS so we don't ship Babel (2.9 MB) to the browser.

Takes the inline type="text/babel" script from frontend/index.html, compiles
it with Babel (vendor/babel.min.js via quickjs) and writes frontend/app.js.
Generating frontend/index.html from index.src.html is not required:
index.html stays the source (dev mode); the server serves index.prod.html
if it is newer. Run after every change to index.html:

    python3 tools/build.py
"""
from __future__ import annotations

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FRONT = os.path.join(ROOT, "frontend")


def main() -> None:
    src_path = os.path.join(FRONT, "index.html")
    html = open(src_path, encoding="utf-8").read()

    m = re.search(r'<script type="text/babel"[^>]*>(.*?)</script>', html, re.S)
    if not m:
        sys.exit("index.html: <script type=\"text/babel\"> not found")
    jsx = m.group(1)

    import quickjs
    babel_src = open(os.path.join(FRONT, "vendor", "babel.min.js"),
                     encoding="utf-8").read()
    ctx = quickjs.Context()
    ctx.set_max_stack_size(256 * 1024 * 1024)
    ctx.eval("var console={log:function(){},warn:function(){},error:function(){}};"
             "var self=this; var window=this;")
    ctx.eval(babel_src)
    ctx.set("SRC", jsx)
    ctx.eval("var OUT = Babel.transform(SRC, {presets: ['react']}).code;")
    compiled = ctx.get("OUT")

    with open(os.path.join(FRONT, "app.js"), "w", encoding="utf-8") as f:
        f.write("/* autogenerated by tools/build.py - do not edit */\n")
        f.write(compiled)

    # prod page variant: without babel and without inline JSX;
    # hash in the query - otherwise the browser caches the old app.js and features "disappear"
    import hashlib
    h = hashlib.md5(compiled.encode()).hexdigest()[:10]
    prod = html.replace('<script src="vendor/babel.min.js"></script>\n', "")
    prod = prod.replace(m.group(0), f'<script defer src="app.js?v={h}"></script>')
    with open(os.path.join(FRONT, "index.prod.html"), "w", encoding="utf-8") as f:
        f.write(prod)

    print(f"OK: app.js ({len(compiled)//1024} KB), index.prod.html")


if __name__ == "__main__":
    main()
